// Cuerda 1 (E aguda)

export const notes_images = [
  { image: "images/0 Traste 1.png", answer: "E" },
  { image: "images/1 Traste 1.png", answer: "F" },
  { image: "images/2 Traste 1.png", answer: "F#" },
  { image: "images/3 Traste 1.png", answer: "G" },
  { image: "images/4 Traste 1.png", answer: "G#" },
  { image: "images/5 Traste 1.png", answer: "A" },
  { image: "images/6 Traste 1.png", answer: "A#" },
  { image: "images/7 Traste 1.png", answer: "B" },
  { image: "images/8 Traste 1.png", answer: "C" },
  { image: "images/9 Traste 1.png", answer: "C#" },
  { image: "images/10 Traste 1.png", answer: "D" },
  { image: "images/11 Traste 1.png", answer: "D#" },
  { image: "images/12 Traste 1.png", answer: "E" },

  // Cuerda 2 (B)
  { image: "images/0 Traste 2.png", answer: "B" },
  { image: "images/1 Traste 2.png", answer: "C" },
  { image: "images/2 Traste 2.png", answer: "C#" },
  { image: "images/3 Traste 2.png", answer: "D" },
  { image: "images/4 Traste 2.png", answer: "D#" },
  { image: "images/5 Traste 2.png", answer: "E" },
  { image: "images/6 Traste 2.png", answer: "F" },
  { image: "images/7 Traste 2.png", answer: "F#" },
  { image: "images/8 Traste 2.png", answer: "G" },
  { image: "images/9 Traste 2.png", answer: "G#" },
  { image: "images/10 Traste 2.png", answer: "A" },
  { image: "images/11 Traste 2.png", answer: "A#" },
  { image: "images/12 Traste 2.png", answer: "B" },

  // Cuerda 3 (G)
  { image: "images/0 Traste 3.png", answer: "G" },
  { image: "images/1 Traste 3.png", answer: "G#" },
  { image: "images/2 Traste 3.png", answer: "A" },
  { image: "images/3 Traste 3.png", answer: "A#" },
  { image: "images/4 Traste 3.png", answer: "B" },
  { image: "images/5 Traste 3.png", answer: "C" },
  { image: "images/6 Traste 3.png", answer: "C#" },
  { image: "images/7 Traste 3.png", answer: "D" },
  { image: "images/8 Traste 3.png", answer: "D#" },
  { image: "images/9 Traste 3.png", answer: "E" },
  { image: "images/10 Traste 3.png", answer: "F" },
  { image: "images/11 Traste 3.png", answer: "F#" },
  { image: "images/12 Traste 3.png", answer: "G" },

  // Cuerda 4 (D)
  { image: "images/0 Traste 4.png", answer: "D" },
  { image: "images/1 Traste 4.png", answer: "D#" },
  { image: "images/2 Traste 4.png", answer: "E" },
  { image: "images/3 Traste 4.png", answer: "F" },
  { image: "images/4 Traste 4.png", answer: "F#" },
  { image: "images/5 Traste 4.png", answer: "G" },
  { image: "images/6 Traste 4.png", answer: "G#" },
  { image: "images/7 Traste 4.png", answer: "A" },
  { image: "images/8 Traste 4.png", answer: "A#" },
  { image: "images/9 Traste 4.png", answer: "B" },
  { image: "images/10 Traste 4.png", answer: "C" },
  { image: "images/11 Traste 4.png", answer: "C#" },
  { image: "images/12 Traste 4.png", answer: "D" },

  // Cuerda 5 (A)
  { image: "images/0 Traste 5.png", answer: "A" },
  { image: "images/1 Traste 5.png", answer: "A#" },
  { image: "images/2 Traste 5.png", answer: "B" },
  { image: "images/3 Traste 5.png", answer: "C" },
  { image: "images/4 Traste 5.png", answer: "C#" },
  { image: "images/5 Traste 5.png", answer: "D" },
  { image: "images/6 Traste 5.png", answer: "D#" },
  { image: "images/7 Traste 5.png", answer: "E" },
  { image: "images/8 Traste 5.png", answer: "F" },
  { image: "images/9 Traste 5.png", answer: "F#" },
  { image: "images/10 Traste 5.png", answer: "G" },
  { image: "images/11 Traste 5.png", answer: "G#" },
  { image: "images/12 Traste 5.png", answer: "A" },

  // Cuerda 6 (E grave)
  { image: "images/0 Traste 6.png", answer: "E" },
  { image: "images/1 Traste 6.png", answer: "F" },
  { image: "images/2 Traste 6.png", answer: "F#" },
  { image: "images/3 Traste 6.png", answer: "G" },
  { image: "images/4 Traste 6.png", answer: "G#" },
  { image: "images/5 Traste 6.png", answer: "A" },
  { image: "images/6 Traste 6.png", answer: "A#" },
  { image: "images/7 Traste 6.png", answer: "B" },
  { image: "images/8 Traste 6.png", answer: "C" },
  { image: "images/9 Traste 6.png", answer: "C#" },
  { image: "images/10 Traste 6.png", answer: "D" },
  { image: "images/11 Traste 6.png", answer: "D#" },
  { image: "images/12 Traste 6.png", answer: "E" },
];
