-- =====================================================================
-- Las preguntas del trivial
-- Ejecutar DESPUES de db/trivia.sql. Se puede repetir sin miedo.
-- =====================================================================
-- Este archivo esta GENERADO. No se edita a mano: a partir de aqui las
-- preguntas se anaden desde el panel de Supabase, importando un CSV con el
-- formato de db/trivia_plantilla.csv.
--
-- De donde sale cada cosa:
--   * las que ya estaban en app/play/trivia/preguntasTrivial.tsx, repartidas
--     por temas (eran casi todas de guitarra y de grupos);
--   * las 100 de la hoja de calculo, con tres filas recompuestas: una coma
--     dentro del texto habia corrido las columnas y se habia perdido una
--     opcion;
--   * las escritas para llenar los temas que no tenian ninguna.
--
-- El `on conflict do nothing` se apoya en el indice unico sobre la pregunta:
-- volver a pasar el archivo no duplica nada.
-- =====================================================================

begin;

insert into trivia_questions (tema, pregunta, opcion_1, opcion_2, opcion_3, opcion_4, correcta) values
  ('guitarra', '¿Qué guitarrista es conocido por su icónica Fender Stratocaster negra llamada ''Blackie''?', 'Eric Clapton', 'Jeff Beck', 'Ritchie Blackmore', 'Jimi Hendrix', 1),
  ('historia', '¿En qué banda militaron juntos Michael Schenker y su hermano Rudolf?', 'Europe', 'Scorpions', 'UFO', 'MSG', 2),
  ('historia', '¿Qué famosa respuesta dio Jimi Hendrix cuando le preguntaron qué se sentía al ser el mejor guitarrista del mundo?', '''Es un honor''', '''No lo sé, preguntadle a Rory Gallagher''', '''Prefiero a Eric Clapton''', '''Solo soy un músico''', 2),
  ('guitarra', '¿Cómo se llama la famosa Gibson Les Paul de 1959 que perteneció a Peter Green y luego a Gary Moore?', 'Lucy', 'Pearly Gates', 'Greeny', 'Blackie', 3),
  ('historia', '¿Qué guitarrista alemán grabó el legendario álbum en directo ''Tokyo Tapes'' con Scorpions en 1978?', 'Uli Jon Roth', 'Michael Schenker', 'Rudolf Schenker', 'Matthias Jabs', 1),
  ('guitarra', '¿Cómo se llama el revolucionario solo instrumental de Eddie Van Halen que cambió la guitarra eléctrica en 1978?', 'Cathedral', 'Spanish Fly', 'Mean Street', 'Eruption', 4),
  ('guitarra', '¿Qué modelo de guitarra eléctrica, famosa por tener el acabado casi totalmente desgastado, era la seña de identidad de Rory Gallagher?', 'Vox Phantom', 'Fender Stratocaster 1961', 'Gibson Les Paul Junior', 'Fender Telecaster 1952', 2),
  ('historia', '¿Qué guitarrista alemán de los años 70 es citado a menudo como una gran influencia temprana en el estilo de Eddie Van Halen?', 'Uli Jon Roth', 'Michael Schenker', 'Rudolf Schenker', 'Wolf Hoffmann', 1),
  ('historia', '¿Qué banda incluía una cláusula en su contrato exigiendo un bol de M&Ms sin caramelos marrones para verificar la seguridad del escenario?', 'Aerosmith', 'Led Zeppelin', 'Van Halen', 'Mötley Crüe', 3),
  ('guitarra', '¿Qué afinación abierta utiliza Jimmy Page en la canción ''Kashmir'' para lograr ese sonido épico y oriental?', 'Open G', 'DADGAD', 'Drop D', 'Open E', 2),
  ('grabacion', '¿Qué banda británica fue pionera en separar drásticamente los instrumentos en la mezcla (ej. batería a un lado, guitarras al otro) en sus primeros discos?', 'The Rolling Stones', 'Led Zeppelin', 'The Beatles', 'The Who', 3),
  ('guitarra', '¿En qué legendaria canción de Van Halen se escucha a Eddie bajando la sexta cuerda a un Re (Drop D) en mitad del riff?', 'Panama', 'Ain''t Talkin'' ''bout Love', 'Runnin'' with the Devil', 'Unchained', 4),
  ('guitarra', '¿Qué técnica popularizó masivamente Eddie Van Halen utilizando ambas manos en el mástil?', 'Slide', 'Sweep Picking', 'Tapping', 'Chicken Picking', 3),
  ('guitarra', '¿Cómo se llama la guitarra icónica de rayas blancas y negras (o rojas) construida por el propio Eddie Van Halen?', 'Wolfgang', 'Frankenstrat', 'Blackie', 'The Log', 2),
  ('historia', '¿En qué canción de Michael Jackson grabó Eddie Van Halen el solo de guitarra de forma gratuita?', 'Bad', 'Beat It', 'Thriller', 'Billie Jean', 2),
  ('guitarra', '¿Qué sistema de puente flotante ayudó a desarrollar Eddie Van Halen para que la guitarra no se desafinara al usar la palanca?', 'Bigsby', 'Wilkinson', 'Floyd Rose', 'Vintage Tremolo', 3),
  ('historia', '¿Qué guitarrista compuso y grabó el tema instrumental ''Jessica'' de The Allman Brothers Band?', 'Warren Haynes', 'Derek Trucks', 'Dickey Betts', 'Duane Allman', 3),
  ('historia', '¿Qué joven prodigio de la guitarra grabó los álbumes ''Blizzard of Ozz'' y ''Diary of a Madman'' con Ozzy Osbourne?', 'Tony Iommi', 'Zakk Wylde', 'Jake E. Lee', 'Randy Rhoads', 4),
  ('historia', '¿En qué legendario álbum en directo de UFO se puede escuchar la mejor versión de ''Rock Bottom'' de Michael Schenker?', 'Force It', 'Phenomenon', 'Strangers in the Night', 'No Heavy Petting', 3),
  ('historia', '¿Qué guitarrista de los Allman Brothers falleció trágicamente en un accidente de moto en 1971, poco después del álbum ''At Fillmore East''?', 'Duane Allman', 'Butch Trucks', 'Berry Oakley', 'Gregg Allman', 1),
  ('guitarra', '¿Qué técnica de guitarra, de la cual Duane Allman era un maestro absoluto, define el sonido de ''Statesboro Blues''?', 'Slide (con un bote de cristal de Coricidin)', 'Sweep Picking', 'Tapping', 'Fingerpicking', 1),
  ('historia', '¿Quién es el actual guitarrista de la ''Tedeschi Trucks Band'' y sobrino de uno de los fundadores de los Allman Brothers?', 'Derek Trucks', 'Joe Bonamassa', 'Marcus King', 'Kenny Wayne Shepherd', 1),
  ('guitarra', '¿Cuál fue la primera guitarra de cuerpo sólido comercializada masivamente por Leo Fender?', 'Telecaster', 'Broadcaster', 'Stratocaster', 'Jazzmaster', 2),
  ('historia', '¿Qué álbum de ''The Beatles'' incluye el famoso solo de Eric Clapton en ''While My Guitar Gently Weeps''?', 'Revolver', 'Abbey Road', 'Let It Be', 'The White Album', 4),
  ('historia', '¿Qué guitarrista británico grabó la famosa versión de ''Hideaway'' en 1966?', 'Jimmy Page', 'Peter Green', 'Jeff Beck', 'Eric Clapton', 4),
  ('historia', '¿Qué legendario ''King'' del blues grabó e hizo famosa originalmente la canción instrumental ''The Stumble'' en 1961?', 'Freddie King', 'Earl King', 'Albert King', 'B.B. King', 1),
  ('guitarra', '¿Qué modelo de Gibson es inseparable de la imagen de Jimmy Page?', 'SG', 'Flying V', 'Explorer', 'Les Paul Standard', 4),
  ('historia', '¿Quién compuso y grabó el legendario solo de ''Sultans of Swing''?', 'Mark Knopfler', 'Gary Moore', 'David Gilmour', 'Jeff Beck', 1),
  ('guitarra', '¿Qué guitarrista de Blues es famoso por tocar una Stratocaster llamada ''Number One''?', 'Rory Gallagher', 'Kenny Wayne Shepherd', 'Stevie Ray Vaughan', 'Buddy Guy', 3),
  ('historia', 'Ritchie Blackmore dejó Deep Purple para fundar su propia banda llamada...', 'Dio', 'Black Sabbath', 'Rainbow', 'Whitesnake', 3),
  ('lenguaje', '¿Cuál es el intervalo característico de la escala ''Blues'' que la diferencia de la pentatónica menor?', 'Sexta mayor', 'Cuarta aumentada', 'Segunda mayor', 'Séptima mayor', 2),
  ('guitarra', '¿En qué año se fabricó la primera Fender Stratocaster?', '1950', '1958', '1952', '1954', 4),
  ('historia', '¿Quiénes compusieron la mítica canción ''Hotel California'' de The Eagles?', 'Joe Walsh y Don Henley', 'Don Henley y Randy Meisner', 'Don Felder, Don Henley y Glenn Frey', 'Glenn Frey y Bernie Leadon', 3),
  ('historia', '¿Qué guitarrista de los Beatles utilizó una Fender Stratocaster apodada ''Rocky'' pintada con colores psicodélicos?', 'George Harrison', 'Pete Best', 'John Lennon', 'Paul McCartney', 1),
  ('guitarra', '¿Cómo se llama la famosa guitarra Fender Stratocaster destrozada de Jimi Hendrix que subastaron por millones?', 'Saville Strat', 'Woodstock White', 'Monterey Strat', 'Black Beauty', 3),
  ('guitarra', '¿Qué modelo de guitarra Gibson utiliza casi exclusivamente Marcus King?', 'Explorer', 'SG Standard', 'Les Paul Goldtop', 'ES-345 TD', 4),
  ('guitarra', '¿Qué guitarrista de ZZ Top es conocido por su ''Pearly Gates'', una Les Paul de 1959?', 'Frank Beard', 'Dusty Hill', 'Billy Gibbons', 'Joe Bonamassa', 3),
  ('historia', '¿En qué banda tocó Eric Clapton antes de formar Cream?', 'Led Zeppelin', 'The Kinks', 'The Who', 'The Yardbirds', 4),
  ('historia', '¿Cuál es el nombre del álbum debut de Jimi Hendrix Experience lanzado en 1967?', 'Electric Ladyland', 'Band of Gypsys', 'Axis: Bold as Love', 'Are You Experienced', 4),
  ('historia', '¿Qué guitarrista de The Eagles toca el famoso solo de slide en ''Victim of Love''?', 'Glenn Frey', 'Don Felder', 'Bernie Leadon', 'Joe Walsh', 2),
  ('guitarra', '¿Qué técnica de mano derecha es característica del sonido de ZZ Top y Billy Gibbons?', 'Sweep Picking', 'Pinch Harmonics (Armónicos de púa)', 'Fingerstyle puro', 'Tapping', 2),
  ('amplificacion', '¿Qué amplificadores utilizaba mayoritariamente Jimi Hendrix en directo?', 'Marshall Super Lead (Plexi)', 'Orange Rockerverb', 'Vox AC30', 'Fender Twin Reverb', 1),
  ('historia', '¿En qué legendario festival Jimi Hendrix quemó su Fender Stratocaster negra por primera vez?', 'Isle of Wight', 'Fillmore East', 'Woodstock', 'Monterey Pop Festival', 4),
  ('historia', '¿Qué canción de los Beatles contiene uno de los primeros ejemplos de ''feedback'' o acople de guitarra grabado?', 'Help!', 'A Hard Day''s Night', 'I Feel Fine', 'Ticket to Ride', 3),
  ('historia', '¿Marcus King es considerado un prodigio de qué mezcla de géneros?', 'Indie y Folk', 'Punk y Metal', 'Southern Rock, Blues y Soul', 'Jazz y Country', 3),
  ('historia', '¿Cómo se llama el guitarrista rítmico y fundador de The Eagles que falleció en 2016?', 'Glenn Frey', 'Timothy B. Schmit', 'Randy Meisner', 'Joe Walsh', 1),
  ('amplificacion', '¿Qué pedal de efecto es fundamental para el sonido de Hendrix en ''Voodoo Child (Slight Return)''?', 'Octavia', 'Fuzz Face', 'Wah-Wah', 'Univibe', 3),
  ('historia', '¿En qué ciudad se formó la banda ZZ Top?', 'Memphis, Tennessee', 'Houston, Texas', 'Dallas, Texas', 'Austin, Texas', 2),
  ('historia', '¿Qué guitarrista de The Beatles tocó el solo de guitarra en ''Taxman''?', 'George Harrison', 'Paul McCartney', 'John Lennon', 'Eric Clapton', 2),
  ('guitarra', '¿Qué marca de guitarras acústicas es la preferida históricamente por The Eagles para sus directos?', 'Taylor', 'Martin', 'Gibson', 'Takamine', 4),
  ('historia', '¿Cuál era el apodo de Eric Clapton durante su estancia en los Yardbirds?', 'Slowhand', 'The Raven', 'The King', 'God', 1),
  ('guitarra', '¿Qué guitarrista de los Rolling Stones es famoso por usar una afinación abierta de Sol (Open G) y solo 5 cuerdas?', 'Keith Richards', 'Mick Taylor', 'Ronnie Wood', 'Brian Jones', 1),
  ('guitarra', '¿Cómo apodó B.B. King a todas sus guitarras Gibson ES-355?', 'Blackie', 'Bernice', 'Lucille', 'Mary Lou', 3),
  ('historia', '¿Qué guitarrista de ''Europe'' grabó el legendario solo de ''The Final Countdown''?', 'Yngwie Malmsteen', 'Vinnie Moore', 'Kee Marcello', 'John Norum', 4),
  ('guitarra', '¿Cuál es el modelo ''Signature'' más famoso de Paul Reed Smith (PRS), diseñado para un guitarrista mexicano?', 'PRS Custom 24', 'PRS Tremonti', 'PRS Santana', 'PRS Dragon', 3),
  ('historia', '¿Qué guitarrista de blues-rock grabó el álbum ''Irish Tour ''74'' con una Stratocaster extremadamente desgastada?', 'Joe Bonamassa', 'Jeff Beck', 'Rory Gallagher', 'Gary Moore', 3),
  ('historia', '¿Quién sustituyó a Ritchie Blackmore en Deep Purple para grabar el álbum ''Come Taste the Band''?', 'David Gilmour', 'Joe Satriani', 'Tommy Bolin', 'Steve Morse', 3),
  ('amplificacion', '¿En qué canción de Jimi Hendrix se escucha por primera vez el efecto Octavia (que dobla la nota una octava arriba)?', 'Purple Haze', 'Voodoo Child', 'Little Wing', 'Fire', 1),
  ('guitarra', '¿Qué marca de guitarras fundó el luthier Grover Jackson, famosa por sus modelos ''Rhoads'' y ''Soloist''?', 'ESP', 'Jackson', 'Charvel', 'Ibanez', 2),
  ('historia', '¿Qué guitarrista pasó por Thin Lizzy y Whitesnake, grabando el superventas álbum homónimo de 1987?', 'Bernie Marsden', 'Micky Moody', 'John Sykes', 'Gary Moore', 3),
  ('guitarra', '¿Qué modelo de Fender utilizaba Jeff Beck en su etapa con The Yardbirds (famosa por tener el cuerpo recortado)?', 'Mustang', 'Esquire', 'Telecaster', 'Stratocaster', 2),
  ('historia', '¿A qué legendario guitarrista de Blues pertenece la frase: ''The Thrill is Gone''?', 'Buddy Guy', 'Muddy Waters', 'John Lee Hooker', 'B.B. King', 4),
  ('historia', '¿Qué guitarrista de los Beatles compuso ''Something'', considerada por Sinatra como la mejor canción de amor?', 'Paul McCartney', 'John Lennon', 'George Harrison', 'Ringo Starr', 3),
  ('historia', '¿Qué guitarrista de Thin Lizzy grabó el famoso solo de ''Parisienne Walkways'' junto a Phil Lynott?', 'John Sykes', 'Gary Moore', 'Scott Gorham', 'Brian Robertson', 2),
  ('guitarra', '¿Qué modelo de guitarra Gibson es la seña de identidad absoluta de Angus Young de AC/DC?', 'SG Standard', 'Les Paul', 'Explorer', 'Flying V', 1),
  ('guitarra', '¿Cuál es el nombre del sistema de vibrato que utiliza Angus Young en algunas de sus Gibson SG antiguas?', 'Bigsby', 'Floyd Rose', 'Kahler', 'Maestro Vibrola', 4),
  ('guitarra', '¿Qué modelo de Fender Stratocaster usaba Jimi Hendrix en el festival de Woodstock (color blanco)?', 'Stratocaster 1968', 'Stratocaster 1962', 'Stratocaster 1970', 'Stratocaster 1954', 1),
  ('guitarra', '¿Qué modelo de Fender es famoso por tener una escala más corta (24 pulgadas), usada por Kurt Cobain?', 'Stratocaster', 'Jaguar', 'Telecaster', 'Jazzmaster', 2),
  ('guitarra', '¿En qué año lanzó Gibson el modelo ''Flying V'', ''Explorer'' y ''Moderne'' por primera vez?', '1961', '1952', '1954', '1958', 4),
  ('guitarra', '¿Cuál era la principal diferencia de la Gibson Les Paul ''Goldtop'' de 1952 respecto a las posteriores?', 'Tenía 3 pastillas', 'El puente era un cordal trapezoidal', 'No tenía pastillas', 'Era de cuerpo hueco', 2),
  ('historia', '¿Qué guitarrista de Scorpions grabó los solos del álbum ''Lovedrive'' antes de dejar la banda definitivamente?', 'Rudolf Schenker', 'Matthias Jabs', 'Uli Jon Roth', 'Michael Schenker', 4),
  ('historia', '¿Qué legendario bluesman se dice que vendió su alma al diablo en un cruce de caminos (Cruce 61 y 49)?', 'Howlin'' Wolf', 'Robert Johnson', 'Son House', 'Muddy Waters', 2),
  ('historia', '¿Quién fue el guitarrista de ''The Who'' famoso por destrozar sus guitarras y hacer el movimiento del ''molinillo''?', 'Pete Townshend', 'Roger Daltrey', 'Keith Moon', 'John Entwistle', 1),
  ('historia', '¿Qué guitarrista de ''The Beatles'' tocaba el bajo originalmente antes de pasar a la guitarra rítmica?', 'John Lennon', 'George Harrison', 'Paul McCartney', 'Ninguno de ellos', 4),
  ('guitarra', '¿Cómo se llama la técnica de tocar la guitarra con un tubo de metal o cristal en el dedo, típica del Blues?', 'Tapping', 'Slide (o Bottleneck)', 'Bending', 'Palm Mute', 2),
  ('guitarra', '¿Qué marca de guitarras compró CBS en 1965, iniciando una era de producción masiva muy criticada?', 'Fender', 'Gretsch', 'Gibson', 'Guild', 1),
  ('historia', '¿Qué guitarrista grabó el solo de ''While My Guitar Gently Weeps'' pero no apareció en los créditos originales?', 'Jeff Beck', 'Jimmy Page', 'Eric Clapton', 'Keith Richards', 3),
  ('historia', '¿Qué guitarrista sustituyó a Mick Taylor en ''The Rolling Stones'' en 1975?', 'Keith Richards', 'Brian Jones', 'Jeff Beck', 'Ronnie Wood', 4),
  ('espana', '¿Qué grupo español logró un gran éxito internacional en 1966 con “Black Is Black”?', 'Los Pekenikes', 'Los Brincos', 'Fórmula V', 'Los Bravos', 4),
  ('espana', '¿Quién fue el cantante principal de Los Bravos en su etapa de mayor éxito?', 'Mike Kennedy', 'Teddy Bautista', 'Miguel Ríos', 'Juan Pardo', 1),
  ('espana', '¿Qué grupo español grabó canciones como “Flamenco” y “Mejor”?', 'Barrabás', 'Los Diablos', 'Los Brincos', 'Canarios', 3),
  ('espana', '¿Qué músico formó parte de Los Brincos antes de desarrollar una exitosa carrera en solitario y en dúo?', 'Juan Pardo', 'Antonio Vega', 'Rosendo Mercado', 'Manolo García', 1),
  ('espana', '¿Qué grupo español de los años 70 destacó por mezclar rock, funk y sonidos de baile?', 'Nacha Pop', 'Barrabás', 'Leño', 'Triana', 2),
  ('espana', '¿Quién fue uno de los principales impulsores de Barrabás?', 'Carlos Tarque', 'Julián Ruiz', 'Teddy Bautista', 'Fernando Arbex', 4),
  ('espana', '¿Qué grupo español grabó “Get On Your Knees” a finales de los años 60?', 'Tequila', 'Canarios', 'Los Bravos', 'Los Diablos', 2),
  ('espana', '¿Quién fue el líder y vocalista más conocido de Canarios?', 'Teddy Bautista', 'Miguel Ríos', 'Alejo Stivel', 'Manolo García', 1),
  ('espana', '¿Qué grupo español fue conocido principalmente por su repertorio instrumental en los años 60?', 'Los Pekenikes', 'Los Brincos', 'Los Bravos', 'Fórmula V', 1),
  ('espana', '¿Qué tema instrumental es uno de los más conocidos de Los Pekenikes?', 'Hilo de seda', 'Un rayo de sol', 'Cuéntame', 'La chica de ayer', 1),
  ('espana', '¿Qué grupo español popularizó “Cuéntame” en 1969?', 'Módulos', 'Los Diablos', 'Los Mustang', 'Fórmula V', 4),
  ('espana', '¿Qué grupo español hizo famoso “Un rayo de sol” en 1970?', 'Los Diablos', 'Canarios', 'Los Brincos', 'Barrabás', 1),
  ('espana', '¿Qué cantante español popularizó “Bienvenidos” y una versión de “Song of Joy”?', 'Víctor Manuel', 'Nino Bravo', 'Miguel Ríos', 'Camilo Sesto', 3),
  ('espana', '¿Qué grupo andaluz fue pionero en fusionar rock progresivo y flamenco?', 'Nacha Pop', 'Leño', 'Tequila', 'Triana', 4),
  ('espana', '¿Quién fue el cantante y teclista de Triana?', 'Jesús de la Rosa', 'Rosendo Mercado', 'Antonio Vega', 'Javier Gurruchaga', 1),
  ('espana', '¿Qué grupo madrileño lideró Rosendo Mercado antes de su carrera en solitario?', 'Tequila', 'Burning', 'Radio Futura', 'Leño', 4),
  ('espana', '¿Qué grupo español de finales de los 70 contó con Alejo Stivel y Ariel Rot?', 'Tequila', 'Burning', 'Los Secretos', 'Nacha Pop', 1),
  ('espana', '¿Qué canción de Nacha Pop se convirtió en un clásico del pop-rock español?', 'Escuela de calor', 'La chica de ayer', 'Venecia', 'Déjame', 2),
  ('espana', '¿Quién compuso y cantó “La chica de ayer”?', 'Enrique Urquijo', 'Carlos Goñi', 'Antonio Vega', 'Santiago Auserón', 3),
  ('espana', '¿Qué grupo español grabó “Escuela de calor”?', 'Radio Futura', 'Hombres G', 'Gabinete Caligari', 'La Unión', 1),
  ('espana', '¿Qué grupo español alcanzó enorme popularidad en los 80 con “Devuélveme a mi chica”?', 'Los Secretos', 'Hombres G', 'Duncan Dhu', 'Mecano', 2),
  ('espana', '¿Qué grupo español grabó “Lobo-hombre en París”?', 'La Unión', 'Seguridad Social', 'Mecano', 'Radio Futura', 1),
  ('espana', '¿Qué grupo vasco publicó canciones como “En algún lugar”?', 'Barricada', 'Kortatu', 'Duncan Dhu', 'La Unión', 3),
  ('espana', '¿Qué grupo de la Movida madrileña grabó “Ni tú ni nadie”?', 'Alaska y Dinarama', 'Nacha Pop', 'Mecano', 'Los Secretos', 1),
  ('espana', '¿Qué grupo español publicó “20 de abril” en 1991?', 'Celtas Cortos', 'Seguridad Social', 'Héroes del Silencio', 'Gabinete Caligari', 1),
  ('historia', '¿Qué guitarrista es conocido como “Slowhand”?', 'Eric Clapton', 'Peter Green', 'Jimmy Page', 'Jeff Beck', 1),
  ('historia', '¿Qué banda grabó “Stairway to Heaven”?', 'Deep Purple', 'Black Sabbath', 'Led Zeppelin', 'The Who', 3),
  ('historia', '¿Quién fue el cantante principal de Queen?', 'Robert Plant', 'Roger Daltrey', 'Freddie Mercury', 'David Bowie', 3),
  ('historia', '¿Qué banda lanzó “The Dark Side of the Moon” en 1973?', 'Genesis', 'King Crimson', 'Pink Floyd', 'Yes', 3),
  ('historia', '¿Qué guitarrista lideró The Jimi Hendrix Experience?', 'Ritchie Blackmore', 'Duane Allman', 'Carlos Santana', 'Jimi Hendrix', 4),
  ('historia', '¿Qué banda grabó “Smoke on the Water”?', 'Black Sabbath', 'Cream', 'Deep Purple', 'Free', 3),
  ('historia', '¿Qué grupo estaba formado por John Lennon, Paul McCartney, George Harrison y Ringo Starr?', 'The Who', 'The Animals', 'The Beatles', 'The Kinks', 3),
  ('historia', '¿Qué álbum de The Beatles incluye “Come Together”?', 'Abbey Road', 'Rubber Soul', 'Help!', 'Revolver', 1),
  ('historia', '¿Qué músico fue conocido como “The King of Rock and Roll”?', 'Buddy Holly', 'Little Richard', 'Chuck Berry', 'Elvis Presley', 4),
  ('historia', '¿Qué pionero del rock compuso “Johnny B. Goode”?', 'Chuck Berry', 'Fats Domino', 'Jerry Lee Lewis', 'Bo Diddley', 1),
  ('historia', '¿Qué artista grabó “Purple Haze”?', 'Jeff Beck', 'Carlos Santana', 'Eric Clapton', 'Jimi Hendrix', 4),
  ('historia', '¿Qué banda británica tenía como cantante a Mick Jagger?', 'The Who', 'The Rolling Stones', 'The Kinks', 'Faces', 2),
  ('historia', '¿Qué canción de The Rolling Stones comienza con un célebre riff de guitarra fuzz?', 'Satisfaction', 'Ruby Tuesday', 'Wild Horses', 'Angie', 1),
  ('historia', '¿Qué banda grabó “My Generation”?', 'The Kinks', 'The Yardbirds', 'The Small Faces', 'The Who', 4),
  ('historia', '¿Qué cantante fue el líder de The Doors?', 'Iggy Pop', 'David Byrne', 'Lou Reed', 'Jim Morrison', 4),
  ('historia', '¿Qué guitarrista fue miembro de Cream?', 'Brian May', 'Tony Iommi', 'Eric Clapton', 'Mark Knopfler', 3),
  ('historia', '¿Qué banda incluía a Jack Bruce, Ginger Baker y Eric Clapton?', 'Cream', 'Free', 'Traffic', 'Bad Company', 1),
  ('historia', '¿Qué bluesman grabó “The Thrill Is Gone”?', 'John Lee Hooker', 'B.B. King', 'Robert Johnson', 'Howlin'' Wolf', 2),
  ('historia', '¿Qué músico de blues es famoso por “Boom Boom”?', 'John Lee Hooker', 'T-Bone Walker', 'Muddy Waters', 'Elmore James', 1),
  ('historia', '¿Qué guitarrista está asociado con la canción “Pride and Joy”?', 'Gary Moore', 'Rory Gallagher', 'Johnny Winter', 'Stevie Ray Vaughan', 4),
  ('historia', '¿Qué cantante de soul grabó “Respect” en 1967?', 'Gladys Knight', 'Aretha Franklin', 'Etta James', 'Diana Ross', 2),
  ('historia', '¿Quién grabó “(Sittin’ On) The Dock of the Bay”?', 'Otis Redding', 'Marvin Gaye', 'Wilson Pickett', 'Sam Cooke', 1),
  ('historia', '¿Qué sello discográfico de Detroit fue fundamental para el soul de los años 60?', 'Stax', 'Chess', 'Motown', 'Atlantic', 3),
  ('historia', '¿Qué grupo femenino de Motown tuvo a Diana Ross como cantante principal?', 'The Shirelles', 'The Ronettes', 'Martha and the Vandellas', 'The Supremes', 4),
  ('historia', '¿Qué cantante grabó “What’s Going On”?', 'Marvin Gaye', 'Al Green', 'Curtis Mayfield', 'Stevie Wonder', 1),
  ('historia', '¿Qué artista publicó “Songs in the Key of Life” en 1976?', 'Isaac Hayes', 'Marvin Gaye', 'Stevie Wonder', 'Prince', 3),
  ('historia', '¿Qué cantante fue conocido como el “Godfather of Soul”?', 'James Brown', 'Sam Cooke', 'Wilson Pickett', 'Ray Charles', 1),
  ('historia', '¿Qué tema de James Brown de 1965 fue decisivo para el desarrollo del funk?', 'Stand by Me', 'Soul Man', 'Papa''s Got a Brand New Bag', 'Try a Little Tenderness', 3),
  ('historia', '¿Qué dúo grabó “Soul Man” en 1967?', 'The Righteous Brothers', 'Hall & Oates', 'Sam & Dave', 'Ike & Tina Turner', 3),
  ('historia', '¿Qué cantante grabó “In the Midnight Hour” en 1965?', 'Al Green', 'Sam Cooke', 'Wilson Pickett', 'Marvin Gaye', 3),
  ('historia', '¿Qué banda de soul/funk grabó “Pick Up the Pieces”?', 'Earth, Wind & Fire', 'Average White Band', 'Commodores', 'Kool & The Gang', 2),
  ('historia', '¿Qué grupo lanzó “September” en 1978?', 'Sly and the Family Stone', 'Chic', 'Kool & The Gang', 'Earth, Wind & Fire', 4),
  ('historia', '¿Qué músico lideró Sly and the Family Stone?', 'Bootsy Collins', 'Sly Stone', 'George Clinton', 'Nile Rodgers', 2),
  ('historia', '¿Qué banda grabó “Le Freak”?', 'Kool & The Gang', 'Sister Sledge', 'Chic', 'The Commodores', 3),
  ('historia', '¿Qué guitarrista y productor fue miembro fundador de Chic?', 'Steve Cropper', 'Eddie Hazel', 'Ernie Isley', 'Nile Rodgers', 4),
  ('historia', '¿Qué artista lanzó “Purple Rain” en 1984?', 'George Michael', 'Prince', 'Michael Jackson', 'Lionel Richie', 2),
  ('historia', '¿Qué álbum de Michael Jackson de 1982 se convirtió en uno de los más vendidos de la historia?', 'Thriller', 'Bad', 'Off the Wall', 'Dangerous', 1),
  ('historia', '¿Qué productor trabajó estrechamente con Michael Jackson en “Thriller”?', 'George Martin', 'Nile Rodgers', 'Phil Spector', 'Quincy Jones', 4),
  ('historia', '¿Qué grupo grabó “Hotel California”?', 'Fleetwood Mac', 'Eagles', 'Journey', 'Boston', 2),
  ('historia', '¿Qué banda publicó “Rumours” en 1977?', 'Eagles', 'Fleetwood Mac', 'Supertramp', 'Toto', 2),
  ('historia', '¿Qué grupo grabó “Africa” en 1982?', 'Toto', 'Boston', 'Foreigner', 'Journey', 1),
  ('historia', '¿Qué banda tenía a Mark Knopfler como guitarrista y cantante?', 'Supertramp', 'Genesis', 'Dire Straits', 'The Police', 3),
  ('historia', '¿Qué canción de Dire Straits incluye la frase “I want my MTV”?', 'Money for Nothing', 'Sultans of Swing', 'Walk of Life', 'Romeo and Juliet', 1),
  ('historia', '¿Qué trío británico estaba formado por Sting, Andy Summers y Stewart Copeland?', 'Cream', 'Genesis', 'The Jam', 'The Police', 4),
  ('historia', '¿Qué banda grabó “Every Breath You Take”?', 'The Police', 'R.E.M.', 'Simple Minds', 'U2', 1),
  ('historia', '¿Qué grupo irlandés publicó “The Joshua Tree” en 1987?', 'The Cranberries', 'Simple Minds', 'U2', 'Thin Lizzy', 3),
  ('historia', '¿Qué cantante lideró U2?', 'Sting', 'Michael Stipe', 'Morrissey', 'Bono', 4),
  ('historia', '¿Qué banda estadounidense grabó “Born to Be Wild”?', 'Creedence Clearwater Revival', 'The Byrds', 'The Doors', 'Steppenwolf', 4),
  ('historia', '¿Qué grupo grabó originalmente “Proud Mary”?', 'The Band', 'The Allman Brothers Band', 'Creedence Clearwater Revival', 'Lynyrd Skynyrd', 3),
  ('historia', '¿Qué banda sureña grabó “Sweet Home Alabama”?', 'Lynyrd Skynyrd', 'Molly Hatchet', 'ZZ Top', 'The Allman Brothers Band', 1),
  ('historia', '¿Qué banda tuvo a Duane Allman y Gregg Allman?', 'Little Feat', 'The Allman Brothers Band', 'Lynyrd Skynyrd', 'The Band', 2),
  ('historia', '¿Qué trío de Texas es conocido por “La Grange”?', 'Cream', 'ZZ Top', 'Grand Funk Railroad', 'Rush', 2),
  ('historia', '¿Qué banda australiana grabó “Back in Black”?', 'Midnight Oil', 'AC/DC', 'INXS', 'Air Supply', 2),
  ('historia', '¿Quién fue el cantante de AC/DC en el álbum “Back in Black”?', 'Brian Johnson', 'Axl Rose', 'Bon Scott', 'Ozzy Osbourne', 1),
  ('historia', '¿Qué banda fue liderada por Ozzy Osbourne en sus primeros años?', 'Rainbow', 'Judas Priest', 'Deep Purple', 'Black Sabbath', 4),
  ('historia', '¿Qué guitarrista de Black Sabbath perdió parte de dos dedos en un accidente industrial?', 'Jimmy Page', 'Michael Schenker', 'Tony Iommi', 'Ritchie Blackmore', 3),
  ('historia', '¿Qué grupo lanzó “Paranoid” en 1970?', 'Deep Purple', 'Black Sabbath', 'Led Zeppelin', 'Uriah Heep', 2),
  ('historia', '¿Qué banda británica grabó “Another One Bites the Dust”?', 'The Clash', 'Dire Straits', 'Queen', 'The Police', 3),
  ('historia', '¿Quién tocaba la guitarra en Queen?', 'Roger Taylor', 'Brian May', 'Freddie Mercury', 'John Deacon', 2),
  ('historia', '¿Qué banda punk británica publicó “London Calling”?', 'Buzzcocks', 'Sex Pistols', 'Ramones', 'The Clash', 4),
  ('historia', '¿Qué grupo neoyorquino popularizó “Blitzkrieg Bop”?', 'Television', 'Talking Heads', 'Ramones', 'Blondie', 3),
  ('historia', '¿Qué cantante lideró Nirvana?', 'Kurt Cobain', 'Layne Staley', 'Chris Cornell', 'Eddie Vedder', 1),
  ('historia', '¿Qué álbum de Nirvana de 1991 incluye “Smells Like Teen Spirit”?', 'Bleach', 'In Utero', 'Incesticide', 'Nevermind', 4),
  ('historia', '¿Qué banda de Seattle grabó “Alive”?', 'Pearl Jam', 'Alice in Chains', 'Mudhoney', 'Soundgarden', 1),
  ('historia', '¿Qué banda lanzó “Superunknown” en 1994?', 'Soundgarden', 'Nirvana', 'Pearl Jam', 'Stone Temple Pilots', 1),
  ('historia', '¿Qué grupo británico publicó “OK Computer” en 1997?', 'Oasis', 'Radiohead', 'Blur', 'Pulp', 2),
  ('historia', '¿Qué banda lanzó “(What’s the Story) Morning Glory?” en 1995?', 'Suede', 'Blur', 'Oasis', 'The Verve', 3),
  ('historia', '¿Qué grupo británico grabó “Song 2”?', 'Blur', 'Oasis', 'Radiohead', 'Pulp', 1),
  ('historia', '¿Qué banda estadounidense publicó “Automatic for the People” en 1992?', 'Talking Heads', 'Pixies', 'Sonic Youth', 'R.E.M.', 4),
  ('historia', '¿Qué cantante fue el líder de R.E.M.?', 'Robert Smith', 'Thom Yorke', 'Morrissey', 'Michael Stipe', 4),
  ('historia', '¿Qué grupo grabó “Under the Bridge” en 1991?', 'Pearl Jam', 'Red Hot Chili Peppers', 'Jane''s Addiction', 'Faith No More', 2),
  ('historia', '¿Qué bajista de Red Hot Chili Peppers es conocido por su estilo de slap?', 'John Paul Jones', 'Flea', 'Geddy Lee', 'Duff McKagan', 2),
  ('historia', '¿Qué grupo de funk-rock grabó “Give It Away”?', 'Primus', 'Red Hot Chili Peppers', 'Extreme', 'Living Colour', 2),
  ('instrumentos', '¿Cuántas cuerdas tiene normalmente una guitarra eléctrica estándar?', '5', '8', '6', '4', 3),
  ('instrumentos', '¿Cuántas cuerdas tiene normalmente un bajo eléctrico estándar?', '5', '6', '4', '8', 3),
  ('amplificacion', '¿Qué válvula de potencia lleva de fábrica un Marshall clásico como el JCM800?', 'EL34', 'EL84', '12AX7', '6V6', 1),
  ('amplificacion', '¿Qué válvula es la más habitual en la etapa de previo de un amplificador de guitarra?', 'EL34', '6L6', 'KT88', '12AX7 (ECC83)', 4),
  ('amplificacion', '¿Qué válvulas de potencia usan la mayoría de los Fender clásicos como el Twin Reverb?', '6550', 'EL34', '6L6', 'EL84', 3),
  ('amplificacion', '¿Qué válvulas de potencia monta el Vox AC30?', 'EL34', '6L6', 'EL84', '6V6', 3),
  ('amplificacion', '¿Cómo se llama la distorsión que aparece al exigirle volumen a la etapa de potencia?', 'Fuzz', 'Compresión óptica', 'Chorus', 'Saturación de potencia', 4),
  ('amplificacion', '¿Para qué sirve un atenuador de potencia?', 'Para saturar la etapa de potencia a volumen bajo', 'Para ecualizar la señal', 'Para subir la ganancia del previo', 'Para eliminar el zumbido', 1),
  ('amplificacion', '¿Qué componente adapta la salida de las válvulas a la impedancia del altavoz?', 'El condensador de paso', 'El transformador de salida', 'La resistencia de cátodo', 'El potenciómetro de volumen', 2),
  ('amplificacion', '¿Qué le puede pasar a un amplificador de válvulas si se enciende sin altavoz conectado?', 'Pierde graves hasta que se conecta', 'No pasa absolutamente nada', 'Puede dañarse el transformador de salida', 'Se apaga solo por seguridad', 3),
  ('amplificacion', '¿Cuál es la impedancia más habitual de un altavoz de guitarra?', '8 ohmios', '50 ohmios', '600 ohmios', '1 ohmio', 1),
  ('amplificacion', '¿Qué altavoz de 12 pulgadas es el más asociado al sonido británico de los años 60 y 70?', 'El Jensen C12N', 'El Celestion Greenback', 'El Eminence Texas Heat', 'El JBL D120', 2),
  ('amplificacion', '¿Qué configuración tiene una pantalla 4x12?', 'Cuatro canales con 12 controles', 'Doce altavoces de 4 pulgadas', 'Cuatro entradas y 12 vatios', 'Cuatro altavoces de 12 pulgadas', 4),
  ('amplificacion', '¿Sobre qué actúa el mando de presencia (presence) de un amplificador?', 'Sobre la reverberación', 'Sobre los agudos de la etapa de potencia', 'Sobre la ganancia del previo', 'Sobre el volumen general', 2),
  ('amplificacion', '¿Cómo genera su efecto una reverb de muelles?', 'Con un altavoz giratorio', 'Mandando la señal por unos muelles metálicos que vibran', 'Con un retardo digital', 'Grabando en una cinta magnética', 2),
  ('amplificacion', '¿Qué modifica un trémolo?', 'El brillo', 'La panorámica', 'El volumen, subiéndolo y bajándolo', 'La afinación', 3),
  ('amplificacion', '¿Y qué modifica un vibrato?', 'La afinación', 'El volumen', 'La ganancia', 'La reverberación', 1),
  ('amplificacion', '¿Qué hace en realidad un pedal de wah-wah?', 'Distorsionar la señal', 'Comprimir la dinámica', 'Barrer un filtro con el movimiento del pie', 'Retardar la señal', 3),
  ('amplificacion', '¿Qué componente da su carácter al Fuzz Face original?', 'Unas válvulas EL84', 'Unos diodos LED', 'Unos transistores de germanio', 'Unos circuitos integrados', 3),
  ('amplificacion', '¿Cuál es el rasgo más reconocible de un Tube Screamer?', 'Que añade reverberación', 'Que solo afecta a los graves', 'Que realza los medios y recorta graves y agudos', 'Que aplana la respuesta por completo', 3),
  ('amplificacion', '¿Para qué sirve el bucle de efectos (FX loop) de un amplificador?', 'Para bajar el volumen sin perder tono', 'Para grabar la señal en el ordenador', 'Para poner efectos entre el previo y la etapa de potencia', 'Para conectar dos guitarras a la vez', 3),
  ('amplificacion', '¿Qué efectos conviene poner en el bucle de efectos y no delante del amplificador?', 'El afinador y el booster', 'El delay y la reverb', 'El wah y el compresor', 'El fuzz y el overdrive', 2),
  ('amplificacion', '¿Qué hace un compresor?', 'Aumentar la distorsión', 'Cortar los agudos', 'Reducir la diferencia entre lo más fuerte y lo más flojo', 'Duplicar la señal', 3),
  ('amplificacion', '¿Qué hace una puerta de ruido (noise gate)?', 'Añadir sustain', 'Silenciar la señal cuando baja de cierto nivel', 'Ecualizar los medios', 'Subir el volumen de las notas flojas', 2),
  ('amplificacion', '¿Qué es un cabezal (head)?', 'Un amplificador con el altavoz dentro', 'Una pantalla de altavoces sin electrónica', 'Un previo sin etapa de potencia', 'Un amplificador sin altavoces, que necesita una pantalla', 4),
  ('amplificacion', '¿Qué es un combo?', 'Una mesa de mezclas pequeña', 'Un amplificador con el altavoz integrado', 'Un pedal con dos efectos', 'Un cabezal más una pantalla', 2),
  ('amplificacion', '¿Qué diferencia a un amplificador de estado sólido de uno de válvulas?', 'Que no lleva altavoz', 'Que solo sirve para bajo', 'Que amplifica con transistores', 'Que no necesita corriente eléctrica', 3),
  ('amplificacion', '¿Qué es el sag en un amplificador de válvulas?', 'La distorsión del previo', 'Un tipo de reverberación', 'Un zumbido de fondo', 'La caída de tensión de la fuente, que suaviza el ataque', 4),
  ('amplificacion', 'Si doblas los vatios de un amplificador, ¿cuánto sube el nivel?', 'Unos 3 dB, que no se percibe como el doble', 'Exactamente el doble', 'No cambia nada', 'Diez veces más', 1),
  ('amplificacion', '¿Qué indica la sensibilidad de un altavoz, medida en dB por vatio a un metro?', 'Cuál es su impedancia', 'Cuántos vatios aguanta', 'Cuánto suena por cada vatio que recibe', 'Cuántos graves da', 3),
  ('amplificacion', '¿Por qué no se debe usar un cable de instrumento para conectar una pantalla?', 'Porque invierte la fase', 'Porque no lleva conector jack', 'Porque siempre es demasiado largo', 'Porque está apantallado y tiene poca sección para esa corriente', 4),
  ('amplificacion', '¿Qué es una IR (respuesta al impulso) en el mundo de la guitarra?', 'Una afinación abierta', 'Un pedal de distorsión', 'Una captura de cómo suena una pantalla microfoneada', 'Un tipo de válvula', 3),
  ('amplificacion', '¿Qué marca de amplificadores fundó Randall Smith?', 'Mesa/Boogie', 'Laney', 'Orange', 'Peavey', 1),
  ('amplificacion', '¿De qué década es el Marshall JCM800, el amplificador de heavy por excelencia?', 'De los años 80', 'De los años 60', 'De los años 2000', 'De los años 50', 1),
  ('amplificacion', '¿Qué amplificador Fender es el ejemplo de manual de canal limpio con reverb de muelles?', 'El Twin Reverb', 'El Bassman', 'El Princeton', 'El Champ', 1),
  ('amplificacion', '¿Qué marca británica es conocida por el color naranja de sus amplificadores?', 'Orange', 'Hiwatt', 'Vox', 'Marshall', 1),
  ('amplificacion', '¿Qué significan las siglas PA en un equipo de sonido?', 'Pre Amplifier', 'Power Amplifier', 'Passive Audio', 'Public Address, la megafonía de sala', 4),
  ('amplificacion', '¿Qué hace el previo de un amplificador?', 'Convierte la señal a digital', 'Rectifica la corriente de red', 'Mueve el cono del altavoz', 'Amplifica y da forma a la señal antes de la etapa de potencia', 4),
  ('amplificacion', '¿Cómo se llama el pitido que aparece cuando la guitarra realimenta al amplificador?', 'Sustain natural', 'Acople o feedback', 'Compresión', 'Trémolo', 2),
  ('amplificacion', '¿Para qué sirve el condensador de brillo (bright cap) del potenciómetro de volumen?', 'Para que no se apaguen los agudos al bajar el volumen', 'Para aumentar la ganancia', 'Para reforzar los graves', 'Para reducir el ruido de red', 1),
  ('amplificacion', '¿Qué válvula convierte la corriente alterna en continua en los amplificadores clásicos?', 'La 6L6', 'La 12AX7', 'La EL34', 'La rectificadora', 4),
  ('amplificacion', '¿Qué es un cabezal lunchbox?', 'Una pantalla de dos altavoces', 'Un pedal que hace de previo', 'Un cabezal diminuto y de poca potencia', 'Un cabezal de más de 100 vatios', 3),
  ('teclados', '¿Cuántas teclas tiene un piano estándar?', '76', '88', '61', '96', 2),
  ('teclados', '¿Cuántas teclas negras hay en una octava?', '6', '7', '5', '4', 3),
  ('teclados', '¿Qué hace el pedal derecho del piano, el que más se usa?', 'Apaga el sonido por completo', 'Sube el volumen general', 'Levanta los apagadores y deja sonar las cuerdas', 'Desplaza el teclado hacia un lado', 3),
  ('teclados', '¿Qué hace el pedal izquierdo (una corda) en un piano de cola?', 'Desplaza el mecanismo para que el macillo golpee menos cuerdas', 'Sostiene todas las notas', 'Afina el instrumento', 'Apaga los agudos', 1),
  ('teclados', '¿Qué hace el pedal central de un piano de cola?', 'Sostiene absolutamente todas las notas', 'Sube el sonido una octava', 'Sostiene solo las notas que estaban pulsadas al pisarlo', 'Sirve para el metrónomo', 3),
  ('teclados', '¿Con qué golpea el piano sus cuerdas?', 'Con un plectro de plástico', 'Con un macillo forrado de fieltro', 'Con un arco de crin', 'Con una púa metálica', 2),
  ('teclados', '¿Cuántas cuerdas suele tener cada nota en el registro agudo de un piano?', 'Cinco', 'Dos', 'Tres', 'Una', 3),
  ('teclados', '¿Qué instrumento antiguo pulsa la cuerda con un plectro en vez de golpearla?', 'El órgano', 'La celesta', 'El clavecín', 'El clavicordio', 3),
  ('teclados', '¿Quién inventó el piano a principios del siglo XVIII?', 'Antonio Stradivari', 'Girolamo Frescobaldi', 'Johann Sebastian Bach', 'Bartolomeo Cristofori', 4),
  ('teclados', '¿De dónde viene el nombre del piano?', 'Del apellido de su inventor', 'Del italiano plano, por su tapa', 'De poder tocar suave y fuerte según la pulsación', 'De la forma de su caja', 3),
  ('teclados', '¿Qué genera el sonido de un Fender Rhodes?', 'Unas ruedas dentadas que giran', 'Unas cuerdas frotadas por un arco', 'Unas varillas metálicas golpeadas por macillos', 'Un oscilador puramente electrónico', 3),
  ('teclados', '¿Qué genera el sonido de un órgano Hammond?', 'Unas ruedas fónicas que giran junto a unas pastillas', 'Unas muestras digitales', 'Unas cuerdas percutidas', 'Unos tubos por los que pasa aire', 1),
  ('teclados', '¿Qué controlan las barras deslizantes (drawbars) de un Hammond?', 'La velocidad del Leslie', 'El volumen general', 'La mezcla de armónicos del sonido', 'La afinación del instrumento', 3),
  ('teclados', '¿Qué es un altavoz Leslie?', 'Una pantalla de cuatro altavoces', 'Un altavoz con la bocina girando, típico del Hammond', 'Un micrófono de cinta', 'Un amplificador de válvulas de 100 vatios', 2),
  ('teclados', '¿En qué canción de Stevie Wonder es protagonista el clavinet?', 'Sir Duke', 'Superstition', 'Higher Ground', 'My Cherie Amour', 2),
  ('teclados', '¿Cómo producía el sonido un Mellotron?', 'Con ruedas fónicas', 'Con osciladores analógicos', 'Con muestras digitales en memoria', 'Reproduciendo una cinta magnética grabada por cada tecla', 4),
  ('teclados', '¿En qué consiste la síntesis sustractiva?', 'En partir de una onda rica en armónicos e ir filtrándolos', 'En sumar ondas senoidales una a una', 'En multiplicar dos frecuencias entre sí', 'En grabar sonidos reales y reproducirlos', 1),
  ('teclados', 'En un sintetizador analógico, ¿qué hace el VCF?', 'Filtrar el sonido', 'Guardar los presets', 'Controlar el volumen', 'Generar la onda', 1),
  ('teclados', '¿Qué significan las siglas ADSR de una envolvente?', 'Agudo, doble, suave y rápido', 'Amplitud, dinámica, sonido y resonancia', 'Análogo, digital, secuencia y ritmo', 'Ataque, caída, sostenimiento y relajación', 4),
  ('teclados', '¿Qué controla el cutoff de un filtro?', 'El volumen de salida', 'El número de voces', 'A partir de qué frecuencia empieza a cortar', 'La velocidad del LFO', 3),
  ('teclados', '¿Qué provoca subir la resonancia de un filtro?', 'Más graves en todo el registro', 'Menos ruido de fondo', 'Más notas simultáneas', 'Un realce en torno a la frecuencia de corte', 4),
  ('teclados', '¿Para qué sirve un LFO en un sintetizador?', 'Para afinar el instrumento', 'Para generar el sonido que se oye', 'Para modular otros parámetros con una oscilación lenta', 'Para grabar secuencias', 3),
  ('teclados', '¿Qué onda contiene solo armónicos impares y suena hueca?', 'La senoidal', 'El ruido blanco', 'La cuadrada', 'La de diente de sierra', 3),
  ('teclados', '¿Qué onda es la más rica en armónicos y la base de las cuerdas sintéticas?', 'La de diente de sierra', 'La senoidal', 'La triangular', 'La cuadrada', 1),
  ('teclados', '¿Qué significa que un sintetizador sea monofónico?', 'Que solo puede sonar una nota a la vez', 'Que no guarda sonidos', 'Que no lleva efectos', 'Que tiene un solo altavoz', 1),
  ('teclados', '¿Qué sintetizador de 1970 popularizó el instrumento portátil y monofónico?', 'El Yamaha DX7', 'El Prophet-5', 'El Roland Juno-106', 'El Minimoog', 4),
  ('teclados', '¿Qué sintetizador fue el primer polifónico programable con memorias?', 'El Hammond B-3', 'El Minimoog', 'El Mellotron', 'El Prophet-5', 4),
  ('teclados', '¿Qué tipo de síntesis usa el Yamaha DX7?', 'Síntesis granular', 'Muestreo de instrumentos reales', 'Síntesis sustractiva', 'Síntesis FM, por modulación de frecuencia', 4),
  ('teclados', '¿Qué máquina de Roland define el sonido del acid house?', 'El SH-101', 'La TR-808', 'El Juno-60', 'La TB-303', 4),
  ('teclados', '¿Qué caja de ritmos de Roland es la más citada en el hip hop y el electro?', 'La CR-78', 'La TB-303', 'El System-100', 'La TR-808', 4),
  ('teclados', '¿En qué año se presentó el estándar MIDI?', 'En 1983', 'En 1975', 'En 1991', 'En 2001', 1),
  ('teclados', '¿Qué transmite un cable MIDI?', 'Corriente para alimentar el sintetizador', 'Órdenes: qué nota, con qué fuerza y cuándo', 'Audio en calidad de CD', 'Una señal de vídeo', 2),
  ('teclados', '¿Cuántos canales tiene el MIDI clásico?', '64', '16', '8', '32', 2),
  ('teclados', '¿Qué hace la rueda de pitch bend?', 'Doblar la afinación hacia arriba o hacia abajo', 'Subir el volumen', 'Cambiar de sonido', 'Activar el arpegiador', 1),
  ('teclados', '¿Qué es un sampler?', 'Un instrumento que reproduce grabaciones a distintas alturas', 'Un tipo de filtro resonante', 'Un secuenciador de pasos', 'Un altavoz giratorio', 1),
  ('teclados', '¿Qué instrumento se toca moviendo las manos sin llegar a tocarlo?', 'El armonio', 'El clavinet', 'El theremin', 'La celesta', 3),
  ('teclados', '¿Qué hace un arpegiador?', 'Añadir reverberación', 'Grabar la interpretación', 'Desgranar automáticamente las notas del acorde que pulsas', 'Doblar las notas una octava abajo', 3),
  ('teclados', '¿Qué significa que un teclado tenga acción contrapesada?', 'Que funciona con pilas', 'Que tiene 88 teclas', 'Que pesa mucho y necesita soporte', 'Que las teclas ofrecen resistencia, como las de un piano', 4),
  ('teclados', '¿Qué es el aftertouch de un teclado?', 'Un efecto de retardo', 'La sensibilidad al golpe inicial', 'El sonido que queda al soltarla', 'La respuesta a la presión una vez pulsada la tecla', 4),
  ('teclados', '¿Qué es un órgano de tubos?', 'Un piano con tubos decorativos', 'Un instrumento que suena haciendo pasar aire por tubos', 'Un sintetizador de los años 70', 'Un órgano eléctrico con ruedas fónicas', 2),
  ('instrumentos', '¿En cuántas grandes familias se divide tradicionalmente la orquesta?', 'Dos: cuerda y viento', 'Tres: cuerda, viento y voz', 'Cinco, contando el piano aparte', 'Cuatro: cuerda, viento madera, viento metal y percusión', 4),
  ('instrumentos', '¿A qué familia pertenece el saxofón?', 'A la percusión', 'Al viento madera', 'A la cuerda', 'Al viento metal', 2),
  ('instrumentos', '¿Por qué el saxofón es viento madera si está hecho de metal?', 'Porque lo inventó un carpintero', 'Porque suena gracias a una lengüeta de caña', 'Porque se toca sentado', 'Porque antiguamente era de madera', 2),
  ('instrumentos', '¿Por qué la flauta travesera es viento madera?', 'Porque tiene llaves', 'Porque se toca en horizontal', 'Porque el sonido nace del aire cortado en un bisel, no de los labios', 'Porque sigue fabricándose en madera', 3),
  ('instrumentos', 'Ordenados del más grave al más agudo, ¿cuál es el orden de la familia del violín?', 'Contrabajo, violonchelo, viola y violín', 'Violonchelo, contrabajo, violín y viola', 'Violín, viola, violonchelo y contrabajo', 'Viola, violín, contrabajo y violonchelo', 1),
  ('instrumentos', '¿Cuántas cuerdas tiene un violín?', 'Tres', 'Seis', 'Cuatro', 'Cinco', 3),
  ('instrumentos', '¿Cómo se afinan las cuerdas del violín, de la más grave a la más aguda?', 'Do, sol, re y la', 'Sol, re, la y mi', 'Mi, la, re y sol', 'La, re, sol y do', 2),
  ('instrumentos', '¿En qué se diferencia la afinación del contrabajo de la del resto de la familia?', 'En que va por cuartas y no por quintas', 'En que tiene cinco cuerdas siempre', 'En que se afina al revés', 'En que va por terceras', 1),
  ('instrumentos', '¿Qué instrumento de metal usa una vara deslizante en lugar de pistones?', 'El trombón', 'La trompa', 'La tuba', 'La trompeta', 1),
  ('instrumentos', '¿Cuántos pistones tiene una trompeta normal?', 'Dos', 'Seis', 'Tres', 'Cuatro', 3),
  ('instrumentos', '¿Qué instrumento de metal se toca con una mano metida en la campana?', 'El trombón', 'La trompa', 'La tuba', 'El fliscorno', 2),
  ('instrumentos', '¿Cuál es el instrumento más grave de la familia del metal?', 'La tuba', 'El bombardino', 'La trompa', 'El trombón', 1),
  ('instrumentos', '¿Qué dos instrumentos usan lengüeta doble?', 'La trompeta y la trompa', 'La flauta y el flautín', 'El clarinete y el saxofón', 'El oboe y el fagot', 4),
  ('instrumentos', '¿Qué dos instrumentos usan lengüeta simple?', 'La flauta y el oboe', 'El oboe y el fagot', 'El corno inglés y el fagot', 'El clarinete y el saxofón', 4),
  ('instrumentos', '¿Qué significa que un instrumento sea transpositor?', 'Que se toca con las dos manos', 'Que suena distinto de lo que está escrito', 'Que cambia de registro con una llave', 'Que se puede afinar en cualquier tono', 2),
  ('instrumentos', 'Si un clarinete en Si bemol lee un do, ¿qué nota suena en realidad?', 'Un do', 'Un la', 'Un re', 'Un si bemol', 4),
  ('instrumentos', '¿Cuál de estos instrumentos de percusión tiene altura definida?', 'La caja', 'Los timbales', 'El bombo', 'Los platos', 2),
  ('instrumentos', '¿En qué se diferencian el xilófono y la marimba?', 'El xilófono es de metal y la marimba de madera', 'El xilófono no tiene resonadores nunca', 'La marimba se toca con arco', 'La marimba tiene láminas más grandes y suena más grave y cálida', 4),
  ('instrumentos', '¿Qué instrumento de láminas lleva un motor que hace vibrar el sonido?', 'La marimba', 'El xilófono', 'El vibráfono', 'El glockenspiel', 3),
  ('instrumentos', '¿Cuántos pedales tiene un arpa de concierto?', 'Siete', 'Tres', 'Cinco', 'Doce', 1),
  ('instrumentos', '¿Cómo se llaman los juegos de tubos que selecciona el organista?', 'Registros', 'Pedales', 'Teclados', 'Manuales', 1),
  ('instrumentos', '¿A qué grupo pertenece el piano según cómo produce el sonido?', 'A la cuerda percutida', 'A la percusión de altura indeterminada', 'A la cuerda frotada', 'A la cuerda pulsada', 1),
  ('instrumentos', '¿Y la guitarra?', 'A la cuerda frotada', 'A la cuerda pulsada', 'Al viento madera', 'A la cuerda percutida', 2),
  ('instrumentos', '¿Cuántas cuerdas tiene un ukelele estándar?', 'Cinco', 'Ocho', 'Cuatro', 'Seis', 3),
  ('instrumentos', '¿Qué tiene de particular el banjo de cinco cuerdas?', 'Que la quinta es más corta y empieza en el quinto traste', 'Que se afina al revés', 'Que se toca con arco', 'Que no tiene trastes', 1),
  ('instrumentos', '¿Cómo están dispuestas las cuerdas de una mandolina?', 'En tres órdenes triples', 'En cuatro órdenes dobles, ocho cuerdas en total', 'En seis cuerdas sueltas', 'En cuatro cuerdas sueltas', 2),
  ('instrumentos', '¿Qué relación hay entre el bajo eléctrico y la guitarra?', 'Suenan igual', 'El bajo suena una octava por debajo', 'El bajo suena una octava por encima', 'El bajo suena una quinta por debajo', 2),
  ('instrumentos', '¿Qué es la tesitura de un instrumento o una voz?', 'El volumen máximo que alcanza', 'La afinación de referencia', 'Su timbre característico', 'El tramo de notas en el que se mueve con comodidad', 4),
  ('instrumentos', '¿Qué es un armónico natural en una cuerda?', 'Un sonido agudo que aparece al tocar la cuerda en ciertos puntos', 'El sonido de dos cuerdas a la vez', 'Un golpe sobre la caja', 'Una nota desafinada', 1),
  ('instrumentos', '¿Para qué sirve la caja de resonancia de un instrumento acústico?', 'Para sujetar el mástil', 'Para amplificar y dar color a la vibración de la cuerda', 'Para guardar las púas', 'Para afinar más rápido', 2),
  ('instrumentos', '¿A qué frecuencia se afina hoy el la de referencia?', '400 Hz', '440 Hz', '432 Hz', '480 Hz', 2),
  ('instrumentos', 'En la clasificación de instrumentos, ¿qué son los cordófonos?', 'Los que suenan por la vibración de una cuerda', 'Los que suenan por el propio material', 'Los que suenan por una columna de aire', 'Los que suenan por una membrana', 1),
  ('instrumentos', '¿Y los idiófonos?', 'Los que tienen cuerdas', 'Los que necesitan una membrana tensada', 'Los que suenan por la vibración de su propio cuerpo', 'Los que se soplan', 3),
  ('instrumentos', '¿Qué es un membranófono?', 'Un instrumento electrónico', 'Un instrumento que suena al vibrar una piel tensada', 'Un instrumento de viento metal', 'Un instrumento de cuerda frotada', 2),
  ('instrumentos', '¿Cuál es el instrumento más grave del viento madera?', 'El saxofón barítono', 'El clarinete bajo', 'El contrafagot', 'El fagot', 3),
  ('instrumentos', '¿Qué instrumento de viento madera es la versión grave del oboe?', 'El corno inglés', 'El flautín', 'El fagot', 'El clarinete', 1),
  ('instrumentos', '¿Qué instrumento es la versión aguda de la flauta travesera?', 'El clarinete piccolo', 'El corno inglés', 'El flautín o piccolo', 'La flauta de pico', 3),
  ('instrumentos', '¿Quién inventó el saxofón?', 'Theobald Boehm', 'Johann Denner', 'Antoine Courtois', 'Adolphe Sax', 4),
  ('instrumentos', '¿Qué instrumento de percusión se afina con un pedal mientras se toca?', 'La caja', 'Los timbales', 'Los bongos', 'El bombo', 2),
  ('instrumentos', '¿Qué instrumento tiene teclas blancas y negras pero suena al soplar aire por unos tubos?', 'La celesta', 'El órgano', 'El piano', 'El acordeón', 2),
  ('orquesta', '¿Cómo se llama el primer violín de una orquesta?', 'El maestro de coro', 'El repertorista', 'El solista', 'El concertino', 4),
  ('orquesta', '¿Dónde se sienta el concertino?', 'A la izquierda del director, en la primera silla', 'Detrás de la percusión', 'A la derecha del director', 'En el centro, delante de todos', 1),
  ('orquesta', '¿Con qué instrumento afina la orquesta antes de empezar?', 'Con la trompeta', 'Con el oboe', 'Con el violín', 'Con el piano', 2),
  ('orquesta', '¿Por qué afina precisamente ese instrumento?', 'Porque es el más antiguo', 'Porque está en el centro', 'Porque su afinación es muy estable y su sonido se oye con claridad', 'Porque es el más caro', 3),
  ('orquesta', '¿Qué nota da la orquesta para afinar?', 'El la', 'El re', 'El do', 'El sol', 1),
  ('orquesta', '¿Cuál es la sección más numerosa de una orquesta sinfónica?', 'La cuerda', 'El viento madera', 'La percusión', 'El viento metal', 1),
  ('orquesta', '¿En cuántos grupos se divide la sección de violines?', 'En dos: primeros y segundos', 'En uno solo', 'En tres', 'En cuatro', 1),
  ('orquesta', '¿Cuántos músicos tiene aproximadamente una orquesta sinfónica?', 'Unos 300', 'Unos 45', 'Entre 80 y 100', 'Unos 20', 3),
  ('orquesta', '¿Qué instrumentos forman un cuarteto de cuerda?', 'Dos violines, una viola y un violonchelo', 'Cuatro violines', 'Dos violines y dos violas', 'Violín, viola, violonchelo y contrabajo', 1),
  ('orquesta', '¿Qué instrumentos forman un quinteto de viento?', 'Cinco trompetas', 'Flauta, oboe, clarinete, fagot y trompa', 'Flauta, oboe, clarinete, fagot y saxofón', 'Trompeta, trombón, tuba, trompa y flauta', 2),
  ('orquesta', '¿Qué significa tutti en una partitura de orquesta?', 'Que se toca muy fuerte', 'Que toca todo el mundo a la vez', 'Que se repite el pasaje', 'Que toca solo un intérprete', 2),
  ('orquesta', '¿Qué quiere decir divisi en una parte de cuerda?', 'Que se toca sin arco', 'Que se toca con sordina', 'Que el grupo se reparte varias notas distintas', 'Que se toca dos veces', 3),
  ('orquesta', '¿Qué es el pizzicato?', 'Tocar con la madera del arco', 'Tocar la cuerda pellizcándola con los dedos', 'Tocar con sordina', 'Tocar cerca del puente', 2),
  ('orquesta', '¿Qué significa col legno?', 'Tocar dos cuerdas a la vez', 'Tocar golpeando la cuerda con la madera del arco', 'Tocar sin vibrato', 'Tocar muy despacio', 2),
  ('orquesta', '¿Para qué sirve una sordina en un instrumento de cuerda o metal?', 'Para afinar más rápido', 'Para apagar y cambiar el timbre del sonido', 'Para subir el volumen', 'Para sujetar el arco', 2),
  ('orquesta', '¿Qué es una partitura general o score?', 'El programa del concierto', 'La parte de un solo instrumento', 'El contrato de los músicos', 'La partitura con todas las voces de la orquesta a la vez', 4),
  ('orquesta', '¿Qué diferencia a una orquesta de cámara de una sinfónica?', 'Que no tiene director', 'Que no lleva cuerda', 'Que tiene muchos menos músicos', 'Que solo toca música moderna', 3),
  ('orquesta', '¿Cuántos movimientos suele tener una sinfonía clásica?', 'Cuatro', 'Uno', 'Dos', 'Seis', 1),
  ('orquesta', '¿Qué es un concierto como forma musical?', 'Cualquier actuación en directo', 'Una obra solo para cuerda', 'Una obra para coro', 'Una obra para solista y orquesta', 4),
  ('orquesta', '¿Qué es una obertura?', 'La pieza orquestal que abre una ópera u obra escénica', 'El ensayo general', 'Un solo de violín', 'El final de una sinfonía', 1),
  ('orquesta', '¿Dónde se coloca la orquesta en una ópera?', 'En el patio de butacas', 'En el escenario, detrás de los cantantes', 'En el foso, delante y debajo del escenario', 'En un palco lateral', 3),
  ('orquesta', '¿Qué compositor introdujo un coro en el último movimiento de su Novena sinfonía?', 'Haydn', 'Beethoven', 'Mozart', 'Brahms', 2),
  ('orquesta', '¿Qué obra de Ravel es un crecimiento continuo sobre el mismo tema repetido?', 'Daphnis y Chloé', 'El Bolero', 'El Concierto para la mano izquierda', 'La Pavana para una infanta difunta', 2),
  ('orquesta', '¿Qué obra de Prokófiev presenta los instrumentos de la orquesta a los niños?', 'El pájaro de fuego', 'El Cascanueces', 'El aprendiz de brujo', 'Pedro y el lobo', 4),
  ('orquesta', '¿Quién compuso la Guía de orquesta para jóvenes?', 'Gustav Mahler', 'Igor Stravinsky', 'Claude Debussy', 'Benjamin Britten', 4),
  ('orquesta', '¿Qué compositor escribió un tratado de instrumentación que sigue siendo referencia?', 'Hector Berlioz', 'Franz Schubert', 'Antonio Vivaldi', 'Frédéric Chopin', 1),
  ('orquesta', '¿Qué es la orquestación?', 'Copiar las partituras', 'Decidir qué instrumentos tocan cada cosa y cómo', 'Dirigir el ensayo', 'Colocar las sillas del escenario', 2),
  ('orquesta', '¿Qué clave leen habitualmente la viola?', 'La clave de fa en cuarta', 'La clave de sol', 'La clave de do en tercera', 'La clave de do en primera', 3),
  ('orquesta', '¿Qué clave leen el violonchelo, el contrabajo y el fagot?', 'La clave de fa en cuarta', 'La clave de do en tercera', 'La clave de do en cuarta', 'La clave de sol', 1),
  ('orquesta', '¿Quién patentó el metrónomo que se usó durante casi dos siglos?', 'Christian Huygens', 'Theobald Boehm', 'Ludwig van Beethoven', 'Johann Maelzel', 4),
  ('orquesta', 'En una indicación de tempo, ¿qué significa allegro?', 'Rápido y animado', 'A velocidad de paseo', 'Muy despacio', 'Solemne', 1),
  ('orquesta', '¿Y adagio?', 'Lento', 'Con fuerza', 'Muy rápido', 'Con alegría', 1),
  ('orquesta', '¿Qué instrumento suele abrir la orquesta por la izquierda del público?', 'La percusión', 'Las trompetas', 'Los contrabajos', 'Los primeros violines', 4),
  ('orquesta', '¿Dónde se sitúa normalmente la percusión?', 'En el centro de la cuerda', 'Delante del director', 'A la izquierda, junto a los violines', 'Al fondo, detrás de todos', 4),
  ('orquesta', '¿Qué hace un maestro de coro?', 'Preparar al coro antes de que llegue el director de orquesta', 'Escribir los arreglos', 'Afinar los instrumentos', 'Dirigir el concierto', 1),
  ('orquesta', '¿Qué es un atril?', 'El soporte donde se apoya la partitura', 'La silla del director', 'El estuche del instrumento', 'La tarima del solista', 1),
  ('orquesta', '¿Qué instrumento no forma parte habitual de la orquesta sinfónica clásica?', 'El saxofón', 'El fagot', 'La trompa', 'El oboe', 1),
  ('orquesta', '¿Qué significa a capella?', 'Cantar en latín', 'Cantar sin acompañamiento instrumental', 'Cantar muy suave', 'Cantar en grupo pequeño', 2),
  ('orquesta', '¿Qué es un solista en un concierto?', 'El músico que toca la parte principal frente a la orquesta', 'El primer trompeta', 'El que dirige desde el violín', 'El músico que afina a los demás', 1),
  ('orquesta', '¿Qué compositor amplió tanto la orquesta que sus sinfonías piden más de cien músicos?', 'Gustav Mahler', 'Wolfgang Amadeus Mozart', 'Johann Pachelbel', 'Joseph Haydn', 1),
  ('grabacion', '¿Qué diferencia principal hay entre un micrófono dinámico y uno de condensador?', 'El dinámico necesita alimentación', 'El dinámico no capta graves', 'El de condensador solo sirve para directo', 'El de condensador es más sensible y necesita alimentación', 4),
  ('grabacion', '¿Qué micrófono es el estándar de toda la vida para microfonear un amplificador de guitarra?', 'El Shure SM58', 'El AKG C414', 'El Shure SM57', 'El Neumann U87', 3),
  ('grabacion', '¿Y cuál es el estándar para la voz en directo?', 'El Shure SM58', 'El Shure SM57', 'El Sennheiser MD421', 'El Neumann U47', 1),
  ('grabacion', '¿Qué es la alimentación phantom?', 'Los 48 voltios que la mesa manda al micrófono de condensador', 'Un efecto de reverberación', 'Un tipo de pila interna', 'La corriente del amplificador', 1),
  ('grabacion', '¿Qué capta un micrófono con patrón cardioide?', 'Solo lo de delante y lo de detrás', 'Todo por igual en cualquier dirección', 'Sobre todo lo que tiene delante', 'Solo lo que tiene a los lados', 3),
  ('grabacion', '¿Y uno omnidireccional?', 'Solo lo de delante', 'Solo lo de detrás', 'Solo lo de los lados', 'Todo por igual, venga de donde venga', 4),
  ('grabacion', '¿Qué patrón polar capta por delante y por detrás, pero no por los lados?', 'El supercardioide', 'El cardioide', 'El omnidireccional', 'El de figura de ocho o bidireccional', 4),
  ('grabacion', '¿Qué es el efecto de proximidad?', 'El refuerzo de graves al acercarse mucho al micrófono', 'El acople que aparece al alejarse', 'La pérdida de agudos con la distancia', 'El eco de la sala', 1),
  ('grabacion', '¿Para qué sirve un filtro antipop delante del micrófono?', 'Para sujetar el micrófono', 'Para aislar del ruido de la calle', 'Para frenar el golpe de aire de las pes y las bes', 'Para subir el volumen', 3),
  ('grabacion', '¿Para qué sirve una caja de inyección o caja DI?', 'Para afinar el bajo', 'Para amplificar la señal a nivel de altavoz', 'Para grabar en cinta', 'Para conectar un instrumento a una entrada de micrófono de forma balanceada', 4),
  ('grabacion', '¿A qué frecuencia de muestreo se graba un CD de audio?', '22.050 Hz', '48.000 Hz', '44.100 Hz', '96.000 Hz', 3),
  ('grabacion', '¿Con cuántos bits por muestra trabaja un CD de audio?', '8 bits', '32 bits', '16 bits', '24 bits', 3),
  ('grabacion', '¿Qué dice el teorema de Nyquist?', 'Que la latencia depende del buffer', 'Que el sonido digital pierde graves', 'Que hay que muestrear al menos al doble de la frecuencia más aguda', 'Que hay que grabar siempre a 24 bits', 3),
  ('grabacion', '¿Qué es la latencia al grabar con ordenador?', 'La pérdida de agudos', 'El tiempo que tarda en guardar el archivo', 'El retardo entre tocar y oírse', 'El ruido de fondo del equipo', 3),
  ('grabacion', 'Si bajas el tamaño del buffer de la tarjeta de sonido, ¿qué pasa?', 'Sube la latencia y mejora el sonido', 'Baja la latencia pero el ordenador sufre más', 'No cambia nada', 'Se graba con más bits', 2),
  ('grabacion', '¿Qué significan las siglas DAW?', 'Convertidor digital', 'Grabadora analógica de doble pista', 'Amplificador digital de onda', 'Estación de trabajo de audio digital', 4),
  ('grabacion', '¿Qué guitarrista fue pionero de la grabación multipista?', 'Charlie Christian', 'Chet Atkins', 'Django Reinhardt', 'Les Paul', 4),
  ('grabacion', '¿Qué es un overdub?', 'Borrar una toma anterior', 'Subir el volumen general', 'Mezclar dos canciones', 'Grabar una pista nueva escuchando las que ya están', 4),
  ('grabacion', '¿Qué se decide con el panorama (pan) de un canal?', 'Si suena más por el altavoz izquierdo o por el derecho', 'Cuánta reverb lleva', 'Cuánto volumen tiene', 'Su ecualización', 1),
  ('grabacion', 'En un compresor, ¿qué indica el umbral (threshold)?', 'El volumen de salida', 'Cuánto reduce la señal', 'A partir de qué nivel empieza a actuar', 'Cuánto tarda en actuar', 3),
  ('grabacion', '¿Y la ratio?', 'Cuánto reduce la señal por encima del umbral', 'A partir de qué nivel actúa', 'Cuánto tarda en soltar', 'Cuánta ganancia añade al final', 1),
  ('grabacion', '¿Qué permite un ecualizador paramétrico que no permita uno gráfico?', 'Subir más los graves', 'Trabajar en estéreo', 'Cortar el ruido', 'Elegir la frecuencia exacta y el ancho de la banda', 4),
  ('grabacion', '¿Qué es una reverb de convolución?', 'Un retardo muy corto', 'Una reverb de placa metálica', 'Una reverb con muelles metálicos', 'Una reverb que usa la respuesta grabada de una sala real', 4),
  ('grabacion', '¿Qué es un slapback?', 'Un eco único y muy corto, típico del rockabilly', 'Una reverb muy larga', 'Una distorsión suave', 'Un efecto de modulación', 1),
  ('grabacion', '¿En qué se diferencia mezclar de masterizar?', 'Mezclar es solo poner efectos', 'Son lo mismo con otro nombre', 'Masterizar es grabar la voz', 'Mezclar equilibra las pistas y masterizar acaba la mezcla ya hecha', 4),
  ('grabacion', '¿A qué se llama guerra del volumen (loudness war)?', 'A la subida de precios de los estudios', 'A los conciertos con más decibelios', 'A la competencia entre marcas de amplificadores', 'A comprimir cada vez más los discos para que suenen más fuerte', 4),
  ('grabacion', 'En digital, ¿qué representa el 0 dBFS?', 'El silencio absoluto', 'El punto de saturación de la cinta', 'El máximo nivel posible antes de distorsionar', 'El nivel medio recomendado', 3),
  ('grabacion', '¿Qué es el clipping digital?', 'El ruido de fondo del previo', 'El recorte que se produce al pasarse del máximo', 'La pérdida de agudos al comprimir', 'Un efecto de retardo', 2),
  ('grabacion', '¿Qué tipo de conexión es un cable XLR?', 'Digital óptica', 'De altavoz', 'No balanceada, con dos polos', 'Balanceada, con tres polos', 4),
  ('grabacion', '¿En qué se diferencia un jack TRS de uno TS?', 'El TS es más largo', 'El TRS tiene un anillo más y puede ser balanceado o estéreo', 'El TRS es solo para auriculares', 'El TS es digital', 2),
  ('grabacion', '¿Qué se buscaba al saturar suavemente la cinta magnética?', 'Grabar más pistas', 'Eliminar el ruido de fondo', 'Reducir el tiempo de grabación', 'Una compresión y un color agradables', 4),
  ('grabacion', '¿Qué canción de 1998 popularizó el uso descarado del Auto-Tune?', 'Vogue, de Madonna', 'Believe, de Cher', 'Frozen, de Madonna', 'Ray of Light, de Madonna', 2),
  ('grabacion', '¿Qué tipo de compresión usa el formato MP3?', 'Con pérdida: tira información que se supone inaudible', 'Solo comprime el silencio', 'Sin pérdida: se reconstruye igual', 'No comprime nada', 1),
  ('grabacion', '¿Cuál de estos formatos guarda el audio sin pérdida?', 'AAC', 'FLAC', 'MP3', 'OGG Vorbis', 2),
  ('grabacion', '¿A cuántas revoluciones por minuto gira un LP de vinilo?', '33 y un tercio', '45', '78', '16', 1),
  ('grabacion', '¿Y un single clásico de vinilo?', '45', '60', '78', '33 y un tercio', 1),
  ('grabacion', '¿Qué es una sala anecoica?', 'Una cabina para la batería', 'La sala donde está la mesa de mezclas', 'Una sala construida para que no haya ningún reflejo de sonido', 'Una sala con mucha reverberación', 3),
  ('grabacion', '¿Qué diferencia hay entre tratar acústicamente una sala e insonorizarla?', 'Tratar mejora cómo suena dentro; insonorizar impide que el sonido salga', 'Son exactamente lo mismo', 'Tratar es más caro siempre', 'Insonorizar solo afecta a los agudos', 1),
  ('grabacion', '¿Para qué sirve un click track al grabar?', 'Para separar las pistas', 'Para afinar los instrumentos', 'Para que todos toquen al mismo tempo', 'Para marcar el volumen máximo', 3),
  ('grabacion', '¿Qué es la relación señal-ruido de un equipo?', 'Su respuesta en frecuencia', 'La distancia entre el sonido útil y el ruido de fondo', 'La cantidad de distorsión que añade', 'Su impedancia de entrada', 2),
  ('lenguaje', '¿Cuántos semitonos hay en una octava?', 'Ocho', 'Veinticuatro', 'Doce', 'Siete', 3),
  ('lenguaje', '¿Cuántos semitonos tiene un tono?', 'Uno', 'Tres', 'Medio', 'Dos', 4),
  ('lenguaje', 'En la escala mayor, ¿entre qué grados están los semitonos?', 'Entre el primero y el segundo, y entre el quinto y el sexto', 'Entre el tercero y el cuarto, y entre el séptimo y el octavo', 'Entre el segundo y el tercero, y entre el sexto y el séptimo', 'Solo entre el séptimo y el octavo', 2),
  ('lenguaje', '¿Cuántas alteraciones tiene la armadura de sol mayor?', 'Un sostenido', 'Dos sostenidos', 'Ninguna', 'Un bemol', 1),
  ('lenguaje', '¿Y la de fa mayor?', 'Un sostenido', 'Ninguna', 'Un bemol', 'Dos bemoles', 3),
  ('lenguaje', '¿En qué orden aparecen los sostenidos en las armaduras?', 'Fa, do, sol, re, la, mi, si', 'Fa, sol, la, si, do, re, mi', 'Do, re, mi, fa, sol, la, si', 'Si, mi, la, re, sol, do, fa', 1),
  ('lenguaje', '¿Y los bemoles?', 'Si, mi, la, re, sol, do, fa', 'Mi, la, re, sol, do, fa, si', 'Fa, do, sol, re, la, mi, si', 'Do, si, la, sol, fa, mi, re', 1),
  ('lenguaje', '¿Cuál es el relativo menor de do mayor?', 'La menor', 'Sol menor', 'Mi menor', 'Re menor', 1),
  ('lenguaje', '¿Qué distancia hay entre una tonalidad mayor y su relativa menor?', 'Una quinta justa por encima', 'Una cuarta justa', 'Una tercera menor por debajo', 'Un tono por debajo', 3),
  ('lenguaje', '¿Qué intervalos forman una tríada mayor?', 'Tercera menor y quinta justa', 'Tercera mayor y quinta justa', 'Tercera menor y quinta disminuida', 'Tercera mayor y quinta aumentada', 2),
  ('lenguaje', '¿Qué distingue a una tríada menor de una mayor?', 'Que se escribe en otra clave', 'Que su quinta es disminuida', 'Que su tercera es menor', 'Que tiene una nota más', 3),
  ('lenguaje', '¿Cómo se forma un acorde disminuido?', 'Con tercera menor y quinta justa', 'Con tercera mayor y quinta aumentada', 'Con tercera menor y quinta disminuida', 'Con tercera mayor y séptima menor', 3),
  ('lenguaje', '¿Y uno aumentado?', 'Con tercera menor y quinta disminuida', 'Con cuarta justa y sexta', 'Con tercera mayor y quinta aumentada', 'Con tercera mayor y séptima mayor', 3),
  ('lenguaje', '¿Qué notas forman un acorde de séptima de dominante?', 'Fundamental, tercera menor, quinta justa y séptima mayor', 'Fundamental, cuarta, quinta y sexta', 'Fundamental, tercera mayor, quinta justa y séptima mayor', 'Fundamental, tercera mayor, quinta justa y séptima menor', 4),
  ('lenguaje', '¿Cuántos semitonos tiene una tercera mayor?', 'Cinco', 'Tres', 'Cuatro', 'Dos', 3),
  ('lenguaje', '¿Y una quinta justa?', 'Ocho', 'Siete', 'Seis', 'Cinco', 2),
  ('lenguaje', '¿Cuántos semitonos tiene el tritono?', 'Siete', 'Seis', 'Cinco', 'Cuatro', 2),
  ('lenguaje', 'Al invertir un intervalo de tercera, ¿qué intervalo sale?', 'Una séptima', 'Una sexta', 'Una cuarta', 'Una quinta', 2),
  ('lenguaje', '¿Qué indica el número de abajo de un compás?', 'En qué tonalidad está la obra', 'Qué figura vale un tiempo', 'Cuántos tiempos hay por compás', 'A qué velocidad se toca', 2),
  ('lenguaje', '¿Qué compás es el del vals?', 'Tres por cuatro', 'Dos por cuatro', 'Cuatro por cuatro', 'Seis por ocho', 1),
  ('lenguaje', '¿Qué tienen en común los compases de subdivisión ternaria como el seis por ocho?', 'Que no llevan armadura', 'Que siempre van muy rápido', 'Que cada tiempo se divide en tres partes', 'Que tienen tres tiempos', 3),
  ('lenguaje', '¿Cuántas negras vale una redonda?', 'Ocho', 'Una', 'Dos', 'Cuatro', 4),
  ('lenguaje', '¿Y cuántas corcheas vale una blanca?', 'Seis', 'Cuatro', 'Dos', 'Ocho', 2),
  ('lenguaje', '¿Qué hace un puntillo detrás de una figura?', 'La convierte en silencio', 'La acorta a la mitad', 'Le añade el doble', 'Le añade la mitad de su valor', 4),
  ('lenguaje', '¿Para qué sirve la ligadura de unión?', 'Para sumar el valor de dos notas de la misma altura', 'Para tocar dos notas distintas seguidas', 'Para repetir un compás', 'Para indicar el matiz', 1),
  ('lenguaje', '¿Qué indica un calderón?', 'Que se toca más fuerte', 'Que se repite desde el principio', 'Que la nota o el silencio se alarga a criterio del intérprete', 'Que se acaba la obra', 3),
  ('lenguaje', '¿En qué línea del pentagrama se coloca la clave de sol?', 'En la segunda', 'En la primera', 'En la cuarta', 'En la tercera', 1),
  ('lenguaje', '¿Cuántas notas tiene una escala pentatónica?', 'Ocho', 'Cinco', 'Siete', 'Seis', 2),
  ('lenguaje', '¿Qué escala usa los doce semitonos seguidos?', 'La cromática', 'La de tonos enteros', 'La diatónica', 'La pentatónica', 1),
  ('lenguaje', '¿Qué caracteriza al modo dórico?', 'Es una escala mayor con la séptima menor', 'Es una escala menor con la segunda menor', 'Es una escala mayor con la cuarta aumentada', 'Es una escala menor con la sexta mayor', 4),
  ('lenguaje', '¿Y al modo mixolidio?', 'Es una escala mayor con la cuarta aumentada', 'Es una escala menor con la quinta disminuida', 'Es una escala menor con la sexta mayor', 'Es una escala mayor con la séptima menor', 4),
  ('lenguaje', '¿Qué modo se caracteriza por su segunda menor?', 'El frigio', 'El lidio', 'El dórico', 'El mixolidio', 1),
  ('lenguaje', '¿Qué grados forman una cadencia perfecta?', 'El quinto y el primero', 'El primero y el quinto', 'El cuarto y el primero', 'El segundo y el cuarto', 1),
  ('lenguaje', '¿Cómo se llama el quinto grado de una tonalidad?', 'Subdominante', 'Tónica', 'Sensible', 'Dominante', 4),
  ('lenguaje', '¿Y el séptimo grado, el que tira hacia la tónica?', 'Dominante', 'Sensible', 'Superdominante', 'Mediante', 2),
  ('lenguaje', 'En el cifrado americano, ¿qué nota es la A?', 'Sol', 'Si', 'Do', 'La', 4),
  ('lenguaje', '¿Y la B?', 'Si', 'Si bemol', 'La', 'Do', 1),
  ('lenguaje', '¿Qué es una anacrusa?', 'El último compás de una obra', 'Un silencio muy largo', 'Una repetición del estribillo', 'Una o varias notas que empiezan antes del primer tiempo fuerte', 4),
  ('lenguaje', '¿Qué es una síncopa?', 'Un sonido que empieza en parte débil y se prolonga sobre la fuerte', 'Un cambio de compás', 'Un silencio en el primer tiempo', 'Una nota muy corta', 1),
  ('lenguaje', 'Ordenados de más flojo a más fuerte, ¿cuál es la secuencia correcta?', 'Forte, piano, mezzoforte', 'Mezzoforte, forte, piano', 'Forte, mezzoforte, piano', 'Piano, mezzoforte, forte', 4),
  ('generos', '¿De cuántos compases es la estructura clásica del blues?', 'Ocho', 'Dieciséis', 'Veinticuatro', 'Doce', 4),
  ('generos', '¿Qué son las blue notes?', 'Las notas del acorde de dominante', 'Las notas graves de la guitarra', 'Notas alteradas que dan al blues su color, como la tercera y la séptima menores', 'Los silencios entre frases', 3),
  ('generos', '¿En qué ciudad se considera que nació el jazz?', 'Memphis', 'Nueva Orleans', 'Nueva York', 'Chicago', 2),
  ('generos', '¿Qué dos músicos son las figuras centrales del bebop?', 'Miles Davis y John Coltrane', 'Duke Ellington y Count Basie', 'Louis Armstrong y Bing Crosby', 'Charlie Parker y Dizzy Gillespie', 4),
  ('generos', '¿Qué formación caracteriza a la era del swing?', 'El dúo de guitarra y voz', 'El trío de piano', 'El cuarteto de saxos', 'La big band', 4),
  ('generos', '¿Qué disco de Miles Davis es la referencia del jazz modal?', 'Bitches Brew', 'Kind of Blue', 'Birth of the Cool', 'Sketches of Spain', 2),
  ('generos', '¿En qué década explotó el rock and roll?', 'En los años 50', 'En los años 60', 'En los años 70', 'En los años 40', 1),
  ('generos', '¿Qué género mezcla el rock and roll con el country de los años 50?', 'El skiffle', 'El doo wop', 'El rockabilly', 'El surf', 3),
  ('generos', '¿Qué guitarrista es el nombre propio del surf rock?', 'Chuck Berry', 'Duane Eddy', 'Link Wray', 'Dick Dale', 4),
  ('generos', '¿De qué ciudad es el sello Motown?', 'Filadelfia', 'Chicago', 'Detroit', 'Memphis', 3),
  ('generos', '¿Dónde cae el acento característico del funk?', 'En el contratiempo', 'En el tercer tiempo', 'En el segundo y el cuarto', 'En el primer tiempo, el famoso the one', 4),
  ('generos', '¿De qué país es originario el reggae?', 'De Jamaica', 'De Trinidad y Tobago', 'De Cuba', 'De Ghana', 1),
  ('generos', '¿Qué caracteriza rítmicamente al reggae y al ska?', 'La ausencia de batería', 'El acento en el primer tiempo', 'El compás de tres por cuatro', 'El acento de la guitarra a contratiempo', 4),
  ('generos', '¿Qué género nace de quitar la voz al reggae y jugar con los efectos en la mesa?', 'El dub', 'El rocksteady', 'El ska', 'El calipso', 1),
  ('generos', '¿En qué década estalla el punk?', 'En los años 80', 'En los años 50', 'En los años 60', 'En los años 70', 4),
  ('generos', '¿Qué banda se considera el punto de partida del heavy metal?', 'Deep Purple', 'Led Zeppelin', 'The Who', 'Black Sabbath', 4),
  ('generos', '¿Qué subgénero del metal encabezaron Metallica, Slayer, Megadeth y Anthrax?', 'El thrash metal', 'El glam metal', 'El doom metal', 'El power metal', 1),
  ('generos', '¿De qué ciudad salió el grunge?', 'De Minneapolis', 'De San Francisco', 'De Portland', 'De Seattle', 4),
  ('generos', '¿En qué país y década se sitúa el britpop?', 'En Estados Unidos de los años 80', 'En el Reino Unido de los años 90', 'En el Reino Unido de los años 70', 'En Australia de los años 90', 2),
  ('generos', '¿En qué barrio de Nueva York nació el hip hop?', 'En Harlem', 'En Queens', 'En Brooklyn', 'En el Bronx', 4),
  ('generos', '¿Qué DJ está considerado uno de los padres fundadores del hip hop?', 'DJ Kool Herc', 'Afrika Bambaataa', 'Grandmaster Flash', 'DJ Premier', 1),
  ('generos', '¿En qué ciudad nació el house?', 'En Nueva York', 'En Berlín', 'En Detroit', 'En Chicago', 4),
  ('generos', '¿Y el techno?', 'En Detroit', 'En Berlín', 'En Manchester', 'En Chicago', 1),
  ('generos', '¿Qué caracteriza al drum and bass?', 'El tempo lento y las guitarras', 'El uso exclusivo de instrumentos acústicos', 'El compás de tres por cuatro', 'Los breaks muy rápidos con líneas de bajo muy graves', 4),
  ('generos', '¿Qué rasgo define al rock progresivo?', 'El uso exclusivo del blues de doce compases', 'Las estructuras largas y los compases irregulares', 'Las canciones de menos de dos minutos', 'La ausencia de teclados', 2),
  ('generos', '¿Qué ciudad es la capital del country?', 'Memphis', 'Nashville', 'Austin', 'Atlanta', 2),
  ('generos', '¿Qué instrumento es la seña de identidad del bluegrass?', 'La armónica', 'El banjo', 'El saxofón', 'El acordeón', 2),
  ('generos', '¿Qué género es la raíz común del soul y del rhythm and blues en las iglesias negras?', 'El zydeco', 'El dixieland', 'El gospel', 'El ragtime', 3),
  ('generos', '¿Qué es la clave en la música cubana y la salsa?', 'Un patrón rítmico de cinco golpes que ordena todo lo demás', 'El instrumento que marca el bajo', 'La introducción de la canción', 'El tono en el que se toca', 1),
  ('generos', '¿De qué país es la bossa nova?', 'De Cuba', 'De Portugal', 'De Argentina', 'De Brasil', 4),
  ('generos', '¿Qué guitarrista y cantante brasileño es la figura clave de la bossa nova?', 'Milton Nascimento', 'Gilberto Gil', 'João Gilberto', 'Caetano Veloso', 3),
  ('generos', '¿Qué instrumento es inseparable del tango?', 'El violonchelo', 'El acordeón diatónico', 'El bandoneón', 'La mandolina', 3),
  ('generos', '¿De cuántos tiempos es el compás de la bulería flamenca?', 'Seis', 'Ocho', 'Cuatro', 'Doce', 4),
  ('generos', '¿De qué país es originaria la cumbia?', 'De México', 'De Venezuela', 'De Colombia', 'De Perú', 3),
  ('generos', '¿Cómo se llama el patrón rítmico sobre el que se construye el reggaetón?', 'El shuffle', 'El tresillo', 'El dembow', 'La clave', 3),
  ('generos', '¿Qué caracteriza rítmicamente a la música disco?', 'La ausencia de bajo', 'El acento a contratiempo', 'El bombo marcando los cuatro tiempos', 'El compás de seis por ocho', 3),
  ('generos', '¿Qué músico está considerado el padre del ambient?', 'Jean-Michel Jarre', 'Philip Glass', 'Brian Eno', 'Kraftwerk', 3),
  ('generos', '¿Qué banda alemana es la referencia fundacional de la música electrónica de baile?', 'Tangerine Dream', 'Kraftwerk', 'Neu!', 'Can', 2),
  ('generos', '¿Qué caracteriza al shoegaze?', 'Las guitarras cubiertas de efectos y la voz enterrada en la mezcla', 'Los solos de guitarra muy largos', 'La ausencia de batería', 'El uso del banjo', 1),
  ('generos', '¿Qué género combina rap y guitarras distorsionadas y triunfó en los años 90?', 'El post-punk', 'El grunge', 'El britpop', 'El nu metal', 4),
  ('guitarra', '¿Cuántos trastes suele tener una Fender Stratocaster clásica?', '27', '24', '21', '18', 3),
  ('guitarra', '¿Qué madera es la más habitual en el cuerpo de una Les Paul?', 'Caoba con tapa de arce', 'Aliso macizo', 'Fresno macizo', 'Cedro', 1),
  ('guitarra', '¿Qué diferencia hay entre una pastilla de bobina simple y una humbucker?', 'La simple es siempre más potente', 'La humbucker lleva dos bobinas y cancela el zumbido', 'La humbucker no lleva imán', 'La simple lleva dos bobinas', 2),
  ('guitarra', '¿Quién inventó la pastilla humbucker para Gibson?', 'Ted McCarty', 'Les Paul', 'Leo Fender', 'Seth Lover', 4),
  ('guitarra', '¿Para qué sirve el alma (truss rod) del mástil?', 'Para corregir la curvatura del mástil', 'Para sujetar las cuerdas', 'Para conectar las pastillas', 'Para afinar la guitarra', 1),
  ('guitarra', '¿Qué es la acción de una guitarra?', 'El ángulo del mástil', 'La fuerza con la que se pulsa', 'La distancia entre trastes', 'La altura de las cuerdas sobre el diapasón', 4),
  ('guitarra', '¿Qué se ajusta al calibrar la octava (intonación) de una guitarra?', 'La curvatura del mástil', 'El grosor de las cuerdas', 'La altura de las pastillas', 'La longitud de cada cuerda desde la cejuela hasta el puente', 4),
  ('guitarra', '¿Qué afinación es la Drop D?', 'Una afinación abierta de re mayor', 'La estándar con la sexta cuerda bajada a re', 'La estándar con la primera bajada a re', 'Todas las cuerdas bajadas un tono', 2),
  ('guitarra', '¿Qué escala tiene una Fender Stratocaster?', '24,75 pulgadas', '24 pulgadas', '27 pulgadas', '25,5 pulgadas', 4),
  ('guitarra', '¿Y una Gibson Les Paul?', '26 pulgadas', '25,5 pulgadas', '24,75 pulgadas', '22 pulgadas', 3),
  ('guitarra', '¿Qué es un puente flotante tipo Floyd Rose?', 'Un puente de guitarra clásica', 'Un puente fijo de latón', 'Un puente sin cejuela', 'Un puente con vibrato y bloqueo de cuerdas para no desafinar', 4),
  ('guitarra', '¿Cuántas cuerdas tiene una guitarra de doce cuerdas por cada nota?', 'Una, con doce afinaciones', 'Tres, en cuatro órdenes', 'Cuatro, en tres órdenes', 'Dos, agrupadas en seis órdenes', 4),
  ('guitarra', '¿Qué se hace al aplicar la técnica de palm mute?', 'Tapar los trastes con el pulgar', 'Golpear las cuerdas con la palma', 'Apoyar el canto de la mano sobre las cuerdas junto al puente', 'Tocar solo con la mano izquierda', 3),
  ('guitarra', '¿Qué es un capo o cejilla?', 'Una pastilla adicional', 'Un tipo de púa', 'Una pinza que sube la afinación pisando todas las cuerdas en un traste', 'Un afinador de pinza', 3),
  ('guitarra', '¿En qué se diferencia una guitarra clásica de una acústica de acero?', 'La acústica no tiene caja', 'La clásica lleva cuerdas de acero', 'La clásica siempre es eléctrica', 'La clásica lleva cuerdas de nailon y mástil más ancho', 4),
  ('espana', '¿Qué grupo sevillano fundó Jesús de la Rosa y mezcló flamenco y rock progresivo?', 'Alameda', 'Triana', 'Smash', 'Medina Azahara', 2),
  ('espana', '¿Qué banda madrileña lideró Rosendo antes de su carrera en solitario?', 'Barón Rojo', 'Topo', 'Leño', 'Asfalto', 3),
  ('espana', '¿Qué grupo publicó Chica de ayer y es emblema de la movida madrileña?', 'Los Secretos', 'Alaska y los Pegamoides', 'Nacha Pop', 'Radio Futura', 3),
  ('espana', '¿Qué banda lideraron los hermanos Auserón?', 'Duncan Dhu', 'Radio Futura', 'Gabinete Caligari', 'La Unión', 2),
  ('espana', '¿Qué grupo vasco formaron Mikel Erentxun y Diego Vasallo?', 'Duncan Dhu', 'La Frontera', 'Los Ronaldos', 'El Último de la Fila', 1),
  ('espana', '¿Quiénes formaban el dúo El Último de la Fila?', 'Manolo García y Rosendo', 'Manolo Tena y Manolo García', 'Quimi Portet y Ramoncín', 'Manolo García y Quimi Portet', 4),
  ('espana', '¿Qué grupo lideraba Pau Donés?', 'El Canto del Loco', 'Jarabe de Palo', 'Pereza', 'Estopa', 2),
  ('espana', '¿Qué grupo de heavy español publicó Los Rockeros van al Infierno?', 'Ángeles del Infierno', 'Obús', 'Barón Rojo', 'Sangre Azul', 3),
  ('espana', '¿Qué banda cordobesa es referencia del rock andaluz junto a Triana?', 'Medina Azahara', 'Extremoduro', 'Reincidentes', 'Los Suaves', 1),
  ('espana', '¿Qué grupo lidera Robe Iniesta?', 'Extremoduro', 'Los Suaves', 'Platero y Tú', 'Marea', 1),
  ('espana', '¿De qué provincia es el grupo Marea?', 'De Asturias', 'De Cádiz', 'De Navarra', 'De Cáceres', 3),
  ('espana', '¿Qué guitarrista flamenco revolucionó el género y grabó Entre dos aguas?', 'Vicente Amigo', 'Manolo Sanlúcar', 'Tomatito', 'Paco de Lucía', 4),
  ('espana', '¿Con qué cantaor formó Paco de Lucía una pareja artística histórica?', 'Enrique Morente', 'Camarón de la Isla', 'El Cigala', 'José Mercé', 2),
  ('espana', '¿Qué disco de Camarón de la Isla de 1979 rompió con la ortodoxia flamenca?', 'Potro de rabia y miel', 'Soy gitano', 'La leyenda del tiempo', 'Como el agua', 3),
  ('espana', '¿Qué grupo madrileño formaron Andrés Calamaro y Ariel Rot?', 'Los Rodríguez', 'Tequila', 'Danza Invisible', 'Los Ronaldos', 1),
  ('espana', '¿Qué cantante lideró Mecano junto a los hermanos Cano?', 'Marta Sánchez', 'Ana Torroja', 'Luz Casal', 'Alaska', 2),
  ('espana', '¿Qué grupo gallego lidera Iván Ferreiro?', 'Los Piratas', 'Lagartija Nick', 'Heredeiros da Crus', 'Siniestro Total', 1),
  ('espana', '¿Qué banda granadina grabó el disco Omega junto a Enrique Morente?', 'Lagartija Nick', 'Los Planetas', 'Niños Mutantes', '091', 1),
  ('espana', '¿Qué grupo granadino publicó Una Semana en el Motor de un Autobús?', '091', 'Los Ángeles', 'Lagartija Nick', 'Los Planetas', 4),
  ('espana', '¿Qué cantautor catalán es autor de Mediterráneo?', 'Joan Manuel Serrat', 'Raimon', 'Lluís Llach', 'Joaquín Sabina', 1),
  ('espana', '¿Qué cantautor publicó 19 Días y 500 Noches?', 'Víctor Manuel', 'Joan Manuel Serrat', 'Luis Eduardo Aute', 'Joaquín Sabina', 4),
  ('espana', '¿Qué grupo español ha vendido más discos en el extranjero cantando en inglés?', 'El Canto del Loco', 'La Oreja de Van Gogh', 'Mecano', 'Héroes del Silencio', 4),
  ('espana', '¿Quién es el cantante de Héroes del Silencio?', 'Dani Martín', 'Fito Cabrales', 'Carlos Tarque', 'Enrique Bunbury', 4),
  ('espana', '¿De qué grupo es cantante Carlos Tarque?', 'M-Clan', 'Extremoduro', 'Los Suaves', 'Marea', 1),
  ('espana', '¿De qué ciudad es el grupo M-Clan?', 'De Valencia', 'De Bilbao', 'De Murcia', 'De Sevilla', 3)
on conflict do nothing;

commit;
