//Cuerda1(Eaguda)

export const diapason_data = [
  //Cuerda1(Mi)
  { image: "/assets/diapason_notas/1Traste1.png", answer: "Fa" },
  { image: "/assets/diapason_notas/2Traste1.png", answer: "Fa#/Solb" },
  { image: "/assets/diapason_notas/3Traste1.png", answer: "Sol" },
  { image: "/assets/diapason_notas/4Traste1.png", answer: "Sol#/Lab" },
  { image: "/assets/diapason_notas/5Traste1.png", answer: "La" },
  { image: "/assets/diapason_notas/6Traste1.png", answer: "La#/Sib" },
  { image: "/assets/diapason_notas/7Traste1.png", answer: "Si" },
  { image: "/assets/diapason_notas/8Traste1.png", answer: "Do" },
  { image: "/assets/diapason_notas/9Traste1.png", answer: "Do#/Reb" },
  { image: "/assets/diapason_notas/10Traste1.png", answer: "Re" },
  { image: "/assets/diapason_notas/11Traste1.png", answer: "Re#/Mib" },
  { image: "/assets/diapason_notas/12Traste1.png", answer: "Mi" },

  //Cuerda2(Si)
  { image: "/assets/diapason_notas/1Traste2.png", answer: "Do" },
  { image: "/assets/diapason_notas/2Traste2.png", answer: "Do#/Reb" },
  { image: "/assets/diapason_notas/3Traste2.png", answer: "Re" },
  { image: "/assets/diapason_notas/4Traste2.png", answer: "Re#/Mib" },
  { image: "/assets/diapason_notas/5Traste2.png", answer: "Mi" },
  { image: "/assets/diapason_notas/6Traste2.png", answer: "Fa" },
  { image: "/assets/diapason_notas/7Traste2.png", answer: "Fa#/Solb" },
  { image: "/assets/diapason_notas/8Traste2.png", answer: "Sol" },
  { image: "/assets/diapason_notas/9Traste2.png", answer: "Sol#/Lab" },
  { image: "/assets/diapason_notas/10Traste2.png", answer: "La" },
  { image: "/assets/diapason_notas/11Traste2.png", answer: "La#/Sib" },
  { image: "/assets/diapason_notas/12Traste2.png", answer: "Si" },

  //Cuerda3(Sol)
  { image: "/assets/diapason_notas/1Traste3.png", answer: "Sol#/Lab" },
  { image: "/assets/diapason_notas/2Traste3.png", answer: "La" },
  { image: "/assets/diapason_notas/3Traste3.png", answer: "La#/Sib" },
  { image: "/assets/diapason_notas/4Traste3.png", answer: "Si" },
  { image: "/assets/diapason_notas/5Traste3.png", answer: "Do" },
  { image: "/assets/diapason_notas/6Traste3.png", answer: "Do#/Reb" },
  { image: "/assets/diapason_notas/7Traste3.png", answer: "Re" },
  { image: "/assets/diapason_notas/8Traste3.png", answer: "Re#/Mib" },
  { image: "/assets/diapason_notas/9Traste3.png", answer: "Mi" },
  { image: "/assets/diapason_notas/10Traste3.png", answer: "Fa" },
  { image: "/assets/diapason_notas/11Traste3.png", answer: "Fa#/Solb" },
  { image: "/assets/diapason_notas/12Traste3.png", answer: "Sol" },

  //Cuerda4(Re)
  { image: "/assets/diapason_notas/1Traste4.png", answer: "Re#/Mib" },
  { image: "/assets/diapason_notas/2Traste4.png", answer: "Mi" },
  { image: "/assets/diapason_notas/3Traste4.png", answer: "Fa" },
  { image: "/assets/diapason_notas/4Traste4.png", answer: "Fa#/Solb" },
  { image: "/assets/diapason_notas/5Traste4.png", answer: "Sol" },
  { image: "/assets/diapason_notas/6Traste4.png", answer: "Sol#/Lab" },
  { image: "/assets/diapason_notas/7Traste4.png", answer: "La" },
  { image: "/assets/diapason_notas/8Traste4.png", answer: "La#/Sib" },
  { image: "/assets/diapason_notas/9Traste4.png", answer: "Si" },
  { image: "/assets/diapason_notas/10Traste4.png", answer: "Do" },
  { image: "/assets/diapason_notas/11Traste4.png", answer: "Do#/Reb" },
  { image: "/assets/diapason_notas/12Traste4.png", answer: "Re" },

  //Cuerda5(La)
  { image: "/assets/diapason_notas/1Traste5.png", answer: "La#/Sib" },
  { image: "/assets/diapason_notas/2Traste5.png", answer: "Si" },
  { image: "/assets/diapason_notas/3Traste5.png", answer: "Do" },
  { image: "/assets/diapason_notas/4Traste5.png", answer: "Do#/Reb" },
  { image: "/assets/diapason_notas/5Traste5.png", answer: "Re" },
  { image: "/assets/diapason_notas/6Traste5.png", answer: "Re#/Mib" },
  { image: "/assets/diapason_notas/7Traste5.png", answer: "Mi" },
  { image: "/assets/diapason_notas/8Traste5.png", answer: "Fa" },
  { image: "/assets/diapason_notas/9Traste5.png", answer: "Fa#/Solb" },
  { image: "/assets/diapason_notas/10Traste5.png", answer: "Sol" },
  { image: "/assets/diapason_notas/11Traste5.png", answer: "Sol#/Lab" },
  { image: "/assets/diapason_notas/12Traste5.png", answer: "La" },

  //Cuerda6(Migrave)
  { image: "/assets/diapason_notas/1Traste6.png", answer: "Fa" },
  { image: "/assets/diapason_notas/2Traste6.png", answer: "Fa#/Solb" },
  { image: "/assets/diapason_notas/3Traste6.png", answer: "Sol" },
  { image: "/assets/diapason_notas/4Traste6.png", answer: "Sol#/Lab" },
  { image: "/assets/diapason_notas/5Traste6.png", answer: "La" },
  { image: "/assets/diapason_notas/6Traste6.png", answer: "La#/Sib" },
  { image: "/assets/diapason_notas/7Traste6.png", answer: "Si" },
  { image: "/assets/diapason_notas/8Traste6.png", answer: "Do" },
  { image: "/assets/diapason_notas/9Traste6.png", answer: "Do#/Reb" },
  { image: "/assets/diapason_notas/10Traste6.png", answer: "Re" },
  { image: "/assets/diapason_notas/11Traste6.png", answer: "Re#/Mib" },
  { image: "/assets/diapason_notas/12Traste6.png", answer: "Mi" },
];
